---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_technology_requirements.html 
keywords: technology, requirements, hardware, software, express, c, series, deployment 
summary: FlexPod 익스프레스 시스템에는 하드웨어 및 소프트웨어 구성 요소의 조합이 필요합니다. 또한 FlexPod Express는 하이퍼바이저 노드를 시스템에 추가하는 데 필요한 하드웨어 구성요소를 2개 단위로 설명합니다. 
---
= 기술 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


FlexPod 익스프레스 시스템에는 하드웨어 및 소프트웨어 구성 요소의 조합이 필요합니다. 또한 FlexPod Express는 하이퍼바이저 노드를 시스템에 추가하는 데 필요한 하드웨어 구성요소를 2개 단위로 설명합니다.



== 하드웨어 요구 사항

선택한 하이퍼바이저에 관계없이 모든 FlexPod Express 구성은 동일한 하드웨어를 사용합니다. 따라서 비즈니스 요구사항이 변경되더라도 동일한 FlexPod Express 하드웨어에서 다른 하이퍼바이저를 사용할 수 있습니다.

다음 표에는 FlexPod Express 구성 및 구축에 필요한 하드웨어 구성요소가 나와 있습니다. 솔루션 구현에 사용되는 하드웨어 구성요소는 고객 요구사항에 따라 다를 수 있습니다.

|===
| 하드웨어 | 수량 


| AFF C190 2노드 클러스터 | 1 


| Cisco C220 M5 서버 | 2 


| Cisco Nexus 31108PC-V 스위치 | 2 


| Cisco UCS C220 M5 랙 서버용 Cisco UCS VIC(가상 인터페이스 카드) 1457 | 2 
|===
이 표에는 10GbE 구현을 위한 기본 구성 외에 필요한 하드웨어가 나와 있습니다.

|===
| 하드웨어 | 수량 


| Cisco UCS C220 M5 서버 | 2 


| Cisco VIC 1457 | 2 
|===


== 소프트웨어 요구 사항

다음 표에는 FlexPod 익스프레스 솔루션의 아키텍처를 구현하는 데 필요한 소프트웨어 구성 요소가 나열되어 있습니다.

|===
| 소프트웨어 | 버전 | 세부 정보 


| CIMC(Cisco Integrated Management Controller) | 4.0.4 | Cisco UCS C220 M5 랙 서버용 


| Cisco nenic 드라이버 | 1.0.0.29 | VIC 1457 인터페이스 카드용 


| Cisco NX-OS입니다 | 7.0(3) i7(6) | Cisco Nexus 31108PC-V 스위치용 


| NetApp ONTAP를 참조하십시오 | 9.6 | AFF C190 컨트롤러의 경우 
|===
이 표에는 FlexPod Express의 모든 VMware vSphere 구축에 필요한 소프트웨어가 나열되어 있습니다.

|===
| 소프트웨어 | 버전 


| VMware vCenter Server 어플라이언스 | 6.7U2 


| VMware vSphere ESXi 하이퍼바이저 | 6.7U2 


| ESXi용 NetApp VAAI 플러그인 | 1.1.2 


| NetApp VSC를 기반으로 합니다 | 9.6 
|===