---
sidebar: sidebar 
permalink: express/express-c-series-aff220-deploy_technology_requirements.html 
keywords: technology, requirements, hardware, software, flexpod, express 
summary: FlexPod 익스프레스 시스템에는 하드웨어 및 소프트웨어 구성 요소의 조합이 필요합니다. 또한 FlexPod Express는 하이퍼바이저 노드를 시스템에 추가하는 데 필요한 하드웨어 구성요소를 2개 단위로 설명합니다. 
---
= 기술 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


FlexPod 익스프레스 시스템에는 하드웨어 및 소프트웨어 구성 요소의 조합이 필요합니다. 또한 FlexPod Express는 하이퍼바이저 노드를 시스템에 추가하는 데 필요한 하드웨어 구성요소를 2개 단위로 설명합니다.



== 하드웨어 요구 사항

선택한 하이퍼바이저에 관계없이 모든 FlexPod Express 구성은 동일한 하드웨어를 사용합니다. 따라서 비즈니스 요구사항이 변경되더라도 두 하이퍼바이저 중 하나를 동일한 FlexPod Express 하드웨어에서 실행할 수 있습니다.

다음 표에는 모든 FlexPod Express 구성에 필요한 하드웨어 구성요소가 나와 있습니다.

|===
| 하드웨어 | 수량 


| AFF A220 HA 쌍 | 1 


| Cisco C220 M5 서버 | 2 


| Cisco Nexus 3172P 스위치 | 2 


| C220 M5 서버용 Cisco UCS 가상 인터페이스 카드(VIC) 1387 | 2 


| CVR-QSFP-SFP 10G 어댑터 | 4 
|===
다음 표에는 10GbE 구현을 위한 기본 구성 외에 필요한 하드웨어가 나와 있습니다.

|===
| 하드웨어 | 수량 


| Cisco UCS C220 M5 서버 | 2 


| Cisco VIC 1387 | 2 


| CVR-QSFP-SFP 10G 어댑터 | 4 
|===


== 소프트웨어 요구 사항

다음 표에는 FlexPod Express 솔루션의 아키텍처를 구현하는 데 필요한 소프트웨어 구성 요소가 나열되어 있습니다.

|===
| 소프트웨어 | 버전 | 세부 정보 


| CIMC(Cisco Integrated Management Controller) | 3.1(3G) | Cisco UCS C220 M5 랙 서버용 


| Cisco nenic 드라이버 | 1.0.25.0 | VIC 1387 인터페이스 카드의 경우 


| Cisco NX-OS입니다 | nxos.7.0.3.I7.5.bin | Cisco Nexus 3172P 스위치용 


| NetApp ONTAP를 참조하십시오 | 9.4 | AFF A220 컨트롤러 
|===
다음 표에는 FlexPod Express의 모든 VMware vSphere 구축에 필요한 소프트웨어가 나와 있습니다.

|===
| 소프트웨어 | 버전 


| VMware vCenter Server 어플라이언스 | 6.7 


| VMware vSphere ESXi 하이퍼바이저 | 6.7 


| ESXi용 NetApp VAAI 플러그인 | 1.1.2 
|===