---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: 이 문서에서는 완전히 이중화된 고가용성 FlexPod Express 시스템을 구성하는 방법에 대해 자세히 설명합니다. 이러한 이중화를 반영하기 위해 각 단계에서 구성 요소를 구성 요소 A 또는 구성 요소 B라고 합니다 
---
= 개요
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


이 문서에서는 완전히 이중화된 고가용성 FlexPod Express 시스템을 구성하는 방법에 대해 자세히 설명합니다. 이러한 이중화를 반영하기 위해 각 단계에서 구성 요소를 구성 요소 A 또는 구성 요소 B라고 합니다 예를 들어 컨트롤러 A와 컨트롤러 B는 이 문서에 프로비저닝된 NetApp 스토리지 컨트롤러 2개를 식별합니다. 스위치 A와 스위치 B는 Cisco Nexus 스위치 쌍을 나타냅니다.

또한 서버 A, 서버 B 등으로 순차적으로 구분되는 여러 Cisco UCS 호스트를 프로비저닝하는 단계도 설명합니다.

사용자 환경과 관련된 정보를 단계별로 포함해야 함을 나타내기 위해 명령 구조의 일부로 '\<<text>>'이 표시됩니다. 'VLAN create' 명령은 다음 예를 참조하십시오.

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
이 문서를 사용하여 FlexPod Express 환경을 완전히 구성할 수 있습니다. 이 프로세스에서 다양한 단계를 수행하려면 고객별 명명 규칙, IP 주소 및 VLAN(Virtual Local Area Network) 스키마를 삽입해야 합니다. 다음 표에서는 이 가이드에 설명된 대로 구축에 필요한 VLAN을 설명합니다. 이 표는 특정 사이트 변수를 기반으로 완료할 수 있으며 문서 구성 단계를 구현하는 데 사용할 수 있습니다.


NOTE: 별도의 대역내 및 대역외 관리 VLAN을 사용하는 경우 이러한 VLAN 간에 레이어 3 경로를 만들어야 합니다. 이 검증에서는 공통 관리 VLAN이 사용되었습니다.

|===
| VLAN 이름입니다 | VLAN의 용도 | VLAN ID입니다 |  


| 관리 VLAN | 관리 인터페이스용 VLAN | 3437 | vSwitch0 


| NFS VLAN | NFS 트래픽용 VLAN | 3438 | vSwitch0 


| VMware vMotion VLAN | 가상 머신(VM)을 하나의 물리적 호스트에서 다른 물리적 호스트로 이동하도록 지정된 VLAN | 3441 | vSwitch0 


| VM 트래픽 VLAN | VM 애플리케이션 트래픽용 VLAN | 3442 | vSwitch0 


| iSCSI-A-VLAN | 패브릭 A의 iSCSI 트래픽용 VLAN | 3439 | iSciBootvSwitch 


| iSCSI-B-VLAN | 패브릭 B의 iSCSI 트래픽용 VLAN | 3440 | iSciBootvSwitch 


| 네이티브 VLAN | 태그가 지정되지 않은 프레임이 할당되는 VLAN입니다 | 2 |  
|===
FlexPod Express를 구성하는 동안 VLAN 번호가 필요합니다. VLAN은 "\<<var_xxxx_vlan>>"라고 하며, 여기서 "xxxx"는 VLAN의 목적(예: iSCSI-A)입니다.

이 검증에는 두 개의 vSwitch가 생성됩니다.

다음 표에는 솔루션 vSwitch가 나와 있습니다.

|===
| vSwitch 이름입니다 | 활성 어댑터 | 포트 | MTU | 로드 밸런싱 


| vSwitch0 | Vmnic2, vmnic4 | 기본값(120) | 9000입니다 | IP 해시를 기반으로 하는 라우트입니다 


| iSciBootvSwitch | Vmnic3, vmnic5 | 기본값(120) | 9000입니다 | 발신 가상 포트 ID를 기반으로 하는 라우트입니다. 
|===

NOTE: 로드 밸런싱의 IP 해시 방법을 사용하려면 정적(모드 켜짐) 포트 채널과 함께 SRC-DST-IP EtherChannel을 사용하는 기본 물리적 스위치에 대해 적절한 구성이 필요합니다. 스위치 구성이 잘못되어 연결이 간헐적으로 이루어지는 경우 포트 채널 설정 문제를 해결하는 동안 ESXi 관리 vmkernel 포트와의 통신을 복구하기 위해 Cisco 스위치에서 연결된 두 개의 업링크 포트 중 하나를 일시적으로 종료합니다.

다음 표에는 생성된 VMware VM이 나와 있습니다.

|===
| VM 설명입니다 | 호스트 이름입니다 


| VMware vCenter Server를 참조하십시오 | FlexPod-VCSA를 참조하십시오 


| 가상 스토리지 콘솔 | FlexPod-VSC를 참조하십시오 
|===