---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_components.html 
keywords: storage, controllers, cluster, aff, asa, fas, afx, ontap, interconnect switches, drives, disk, shelves, licensing, options 
summary: NetApp 스토리지 컨트롤러는 부팅 및 애플리케이션 데이터 스토리지 모두를 위한 FlexPod 아키텍처의 스토리지 기반을 제공합니다. NetApp의 구성 요소에는 스토리지 컨트롤러, 클러스터 인터커넥트 스위치, 드라이브 및 디스크 쉘프, 라이센스 옵션이 있습니다. 
---
= NetApp 구성 요소
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 스토리지 컨트롤러는 부팅 및 애플리케이션 데이터 스토리지 모두를 위한 FlexPod 아키텍처의 스토리지 기반을 제공합니다. NetApp의 구성 요소에는 스토리지 컨트롤러, 클러스터 인터커넥트 스위치, 드라이브 및 디스크 쉘프, 라이센스 옵션이 있습니다.



[[netapp-storage-controller-options]]
== NetApp 스토리지 컨트롤러 옵션

이중화된 NetApp FAS, AFF, ASA 또는 AFX 컨트롤러는 FlexPod 아키텍처에 필요합니다. 이러한 컨트롤러는 ONTAP 소프트웨어를 실행합니다. 스토리지 컨트롤러를 주문할 때 원하는 소프트웨어 버전을 컨트롤러에 미리 설치할 수 있습니다. ONTAP의 경우 전체 클러스터를 주문합니다. 전체 클러스터에는 한 쌍의 스토리지 컨트롤러와 클러스터 인터커넥트(스위치 또는 스위치가 없는 클러스터)가 포함됩니다.


NOTE: 스위치가 없는 클러스터 구성은 2노드 구성에서만 지원됩니다. 클러스터 인터커넥트 스위치는 4개 이상의 노드로 구성된 경우에 필요하며, 2노드 구성의 경우 선택 사항입니다.

선택한 스토리지 플랫폼에 따라 다양한 옵션과 구성을 사용할 수 있습니다. 이러한 추가 구성 요소에 대한 자세한 내용은 영업 담당자에게 문의하십시오.

아래 표에 나열된 컨트롤러 제품군은 Cisco Nexus 스위치에 대한 연결이 원활하므로 FlexPod 데이터 센터 솔루션에 사용하기에 적합합니다. 를 참조하십시오 https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^] 각 컨트롤러 모델에 대한 자세한 호환성 정보

|===
| NetApp 스토리지 제품군(FlexPod 데이터센터용) | 모델 | 기술 사양 


.6+| AFF A 시리즈 | AFF A20 .6+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A-Series 데이터시트"] 


| AFF A30 


| AFF A50 


| AFF A70 


| AFF A90 


| AFF A1K 


.3+| AFF C-Series | AFF C30 .3+| https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C-시리즈 데이터시트"] 


| AFF C60 


| AFF C80 


.7+| ASA | ASA A20 .7+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA 데이터시트"] 


| ASA A30 


| ASA C30 


| ASA A50 


| ASA A70 


| ASA A90 


| ASA A1K 


.5+| FAS | FAS2750 .5+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 데이터시트"] 


| FAS2820 


| FAS50 


| FAS70 


| FAS90 


.2+| AFX | AFX 1K .2+| https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["AFX 데이터시트"] 


| AFX 2K 
|===


[[cluster-interconnect-switch-options]]
== 클러스터 인터커넥트 스위치 옵션

다음 표는 FlexPod 아키텍처에서 사용할 수 있는 Nexus 클러스터 인터커넥트 스위치를 나열합니다. FlexPod는 배포되는 ONTAP 버전과 호환되는 경우 Cisco 스위치가 아닌 스위치를 포함하여 ONTAP에서 지원하는 모든 클러스터 스위치를 지원합니다.

지원되는 클러스터 인터커넥트 스위치 목록을 보려면  https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]에서 *제품 > 네트워킹 > 스위치*를 클릭한 다음 *클러스터 InterConnect 스위치*를 선택하십시오. 벤더 유형별로 필터링하고 스위치를 선택한 다음 *결과 보기*를 클릭하면 스위치에 대한 자세한 정보를 볼 수 있습니다.

아래 표는 클러스터 인터커넥트 스위치로 사용할 수 있는 Cisco 스위치 목록입니다.

|===
| 클러스터 인터커넥트 스위치 | 기술 사양 


| Cisco Nexus 9336C-FX2 | https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html["NetApp 설명서: Cisco Nexus 9336C-FX2 스위치"^] 
|===


[[netapp-disk-shelf-and-drive-options]]
== NetApp 디스크 쉘프 및 드라이브 옵션

내장 디스크 쉘프가 없는 스토리지 컨트롤러에는 최소 하나의 NetApp 디스크 쉘프가 필요합니다. 선택한 NetApp 쉘프 유형에 따라 해당 쉘프에서 사용할 수 있는 드라이브 유형이 결정됩니다.


NOTE: 모든 디스크 쉘프와 디스크 부품 번호는 세일즈 담당자에게 문의하십시오.

다음 표에는 FlexPod Datacenter용 NetApp 디스크 쉘프 옵션과 해당 기술 사양에 대한 링크가 나열되어 있습니다.

디스크 쉘프에 지원되는 드라이브 목록을 확인하려면 link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]로 이동하여 *Products > Storage > Shelves* 에서 *ONTAP (AFF, ASA, FAS) or ONTAP (AFX)*를 선택하고, 사용 중인 ONTAP 버전을 선택한 다음, 쉘프 유형(예: *DS212C*)을 선택하고 *Show Results*를 클릭합니다. *Supported Drives*를 클릭하면 특정 ONTAP 버전 및 디스크 쉘프에서 지원되는 드라이브를 확인할 수 있습니다.

|===
| 디스크 쉘프 | 기술 사양 


| DS212C .6+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["디스크 쉘프 및 저장 매체"] 


| DS224C 


| DS460C 


| NS224 


| NS224 w/NSM100B 


| NX224 
|===


[[netapp-software-licensing-options]]
== NetApp 소프트웨어 라이센스 옵션

다음 표는 NetApp 소프트웨어 라이선스 옵션을 보여줍니다.

|===
| NetApp 소프트웨어 라이센스 | 기술 사양 


| AFF, FAS 및 AFX용 ONTAP One .2+| 라이센스 정보에 대한 자세한 내용은 NetApp 세일즈 팀에 문의하십시오. 


| ASA용 ONTAP One for SAN 
|===
NetApp 소프트웨어 라이선스에 대한 자세한 내용은 다음 링크를 참조하십시오: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp 소프트웨어 라이센스"^].



[[netapp-support-licensing-options]]
== NetApp 지원 라이센스 옵션

SupportEdge Premium 라이선스가 필요하며, 해당 라이선스의 부품 번호는 FlexPod 데이터센터 설계에서 선택한 옵션에 따라 다릅니다.

다음 표에는 NetApp AFF, ASA, FAS 및 AFX 스토리지 시스템에 대한 NetApp 지원 라이센스 옵션이 나열되어 있습니다.

|===
| NetApp Support 라이센스 | 기술 사양 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===