---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: 이 섹션에서는 FlexPod 데이터센터 설계에 필요한 전력 요구 사항과 디스크 쉘프 케이블링 지침을 설명합니다. 
---
= 전원 및 케이블링 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 FlexPod 데이터센터 설계에 필요한 전력 요구 사항 및 케이블링 지침을 설명합니다.



[[power-requirements]]
== 전원 요구 사항

FlexPod 데이터 센터의 전원 요구 사항은 FlexPod 데이터 센터 구성이 설치된 위치에 따라 다릅니다.

필요한 최대 전력과 기타 자세한 전력 정보에 대한 자세한 내용은 섹션에 나와 있는 각 하드웨어 구성 요소의 기술 사양을 참조하십시오 link:dc-tech-spec_technical_specifications_and_references.html["기술 사양 및 참조: 하드웨어 구성 요소"].

자세한 Cisco UCS 전력 데이터는  https://ucspowercalculator.cisco.com/["Cisco UCS 전력 계산기"^]을 참조하십시오.

NetApp 스토리지 컨트롤러 전원 데이터는  https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]을 참조하십시오. * 플랫폼*에서 사용하려는 스토리지 플랫폼(예: AFF A90)을 선택하고 ONTAP 버전을 선택한 다음 *결과 보기*를 클릭합니다. 전원 코드 데이터는 *지원되는 전원 코드* 섹션에 나와 있습니다. 크기, 무게, 소비 전력 등에 대한 자세한 내용은 *크기, 무게, 소음, 전력* 섹션을 참조하십시오.



[[cabling-guidelines]]
== 케이블링 지침

이 섹션에서는 FlexPod 데이터센터 설계에 대한 일반적인 케이블링 지침을 제공합니다.

* 컴퓨팅 및 스토리지 연결에 대해 이중화된 연결을 확보하십시오.
* 연결 속도는 연결된 구성 요소의 속도와 호환되어야 합니다.
* 특정 토폴로지에 대한 추가 케이블링 지침은 link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod 데이터센터 토폴로지"^] 섹션을 참조하십시오.


다음 표는 FlexPod Datacenter 설계에 사용할 수 있는 NetApp 디스크 쉘프에 대한 케이블 연결 지침을 제공합니다.

|===


| 디스크 쉘프 | 케이블링 지침 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["SAS 케이블링 규칙"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["NS224 및 NX224 쉘프 요구 사항 및 모범 사례"^] 


| NS224 w/NSM100B 


| NX224 
|===