---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: 이 섹션에서는 FlexPod Express 설계에 필요한 전력 요구 사항과 디스크 쉘프 케이블 연결 지침을 설명합니다. 
---
= 전원 및 케이블링 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 FlexPod Express 설계에 필요한 전력 요구 사항 및 케이블 연결 지침을 설명합니다.



== 전원 요구 사항

FlexPod Express의 전력 요구 사항은 FlexPod Express 구성이 설치된 위치에 따라 다릅니다.

최대 전력 요구량 및 기타 자세한 전력 정보는 각 하드웨어 구성 요소의 link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["기술 사양"^]를 참조하십시오.

Cisco UCS 전원 데이터에 대한 자세한 내용은 를 참조하십시오 http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/["Cisco UCS 전력 계산기"^].

NetApp 스토리지 컨트롤러 전원 데이터는  http://hwu.netapp.com/Controller/Index?platformTypeId=6780858["NetApp Hardware Universe를 참조하십시오"^]을 참조하십시오. *Platforms* 에서 사용하려는 스토리지 플랫폼(예: AFF A20)을 선택하고 ONTAP 버전을 선택한 다음 *Show Results* 를 클릭하십시오. 전원 코드 정보는 *Supported Power Cords* 섹션에 나와 있으며, 크기, 무게, 소비 전력 등에 대한 자세한 내용은 *Size, Weight, Acoustic, Power* 섹션을 참조하십시오.



== 케이블링 지침

이 섹션에서는 FlexPod Express 설계에 대한 일반적인 케이블 연결 지침을 제공합니다.

* 컴퓨팅 및 스토리지 연결에 대해 이중화된 연결을 확보하십시오.
* 연결 속도는 연결된 구성 요소의 속도와 호환되어야 합니다.
* 특정 토폴로지에 대한 추가 케이블링 지침은 link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod Express 토폴로지"^] 섹션을 참조하십시오.


다음 표는 FlexPod Express 설계에 사용할 수 있는 NetApp 디스크 쉘프에 대한 케이블 연결 지침을 제공합니다.

|===


| 디스크 쉘프 | 케이블링 지침 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["SAS 케이블링 규칙"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["NS224 쉘프 요구 사항 및 모범 사례"^] 


| NS224 w/NSM100B 
|===