---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, fas, cimc, configuration, rack, servers, ucs 
summary: 이 섹션에서는 다양한 버전의 FlexPod Express에 대한 최소 하드웨어 요구 사항을 설명합니다. 
---
= 최소 하드웨어 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 다양한 버전의 FlexPod Express에 대한 최소 하드웨어 요구 사항을 설명합니다.



== NetApp FAS 기반 FlexPod Express

NetApp FAS 컨트롤러를 기본 스토리지로 사용하는 FlexPod Express 솔루션의 하드웨어 요구사항에는 이 섹션에 설명된 구성이 포함됩니다.



=== CIMC 기반 구성(독립형 랙 서버)

Cisco 통합 관리 컨트롤러(CIMC) 구성에는 다음과 같은 하드웨어 구성 요소가 포함됩니다.

* 이중화 구성의 10Gbps 표준 이더넷 스위치 2개(Cisco Nexus 31108을 권장하며, Cisco Nexus 3000 및 9000 모델도 지원됨)
* Cisco UCS C-Series 독립형 랙 서버
* AFF C190, AFF A250, FAS2600 또는 FAS 2700 시리즈 컨트롤러 두 대를 고가용성(HA) 쌍 구성으로 2노드 클러스터에 구축




=== Cisco UCS 관리 구성

Cisco UCS 관리 구성에는 다음과 같은 하드웨어 구성 요소가 포함됩니다.

* 10Gbps 표준 이더넷 스위치 2개를 이중화 구성으로 사용합니다(Cisco Nexus 3524 권장).
* Cisco UCS 5108 교류(AC) 블레이드 서버 섀시 1개
* 두 개의 Cisco UCS 6324 패브릭 인터커넥트
* Cisco UCS B-Series servers(최소 4대의 Cisco UCS B200 M5 블레이드 서버)
* HA 페어 구성의 AFF C190, AFF A250, FAS2750 또는 FAS2720 컨트롤러 2개(컨트롤러당 사용 가능한 통합 타겟 어댑터 2[UTA2] 포트 2개 필요)




== FlexPod Express(E-Series 포함)

E-Series 스타터 구성을 사용하는 FlexPod Express의 하드웨어 요구 사항은 다음과 같습니다.

* 두 개의 Cisco UCS 6324 패브릭 인터커넥트
* Cisco UCS Mini 섀시 5108 AC2 또는 DC2 1개(Cisco UCS 6324 패브릭 인터커넥트는 AC2 및 DC2 섀시에서만 지원됨)
* Cisco UCS B-Series 서버(최소 2대의 Cisco UCS B200 M4 블레이드 서버)
* 최소 12개의 디스크 드라이브가 장착된 E-Series E2824 스토리지 시스템의 HA 쌍 구성 1개
* 이중화 구성의 10Gbps 표준 이더넷 스위치 2대(데이터 센터의 기존 스위치를 사용할 수 있음)


이러한 하드웨어 구성 요소는 솔루션의 초기 구성을 구축하는 데 필요하며, 필요에 따라 추가 블레이드 서버와 디스크 드라이브를 추가할 수 있습니다. E-Series E2824 스토리지 시스템은 상위 플랫폼으로 교체할 수 있으며, 올플래시 시스템으로도 운영할 수 있습니다.
