---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, e, series 
summary: 이 섹션에서는 다양한 버전의 FlexPod Express에 대한 연결 요구 사항에 대해 설명합니다. 
---
= 연결 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 다양한 버전의 FlexPod Express에 대한 연결 요구 사항에 대해 설명합니다.



== FlexPod Express with NetApp FAS의 연결 요구 사항

FlexPod Express와 NetApp FAS의 연결 요구 사항은 다음과 같습니다.

* NetApp FAS 스토리지 컨트롤러는 Cisco UCS 관리 구성을 제외하고 Cisco Nexus 스위치에 직접 연결되어야 하며, Cisco UCS 관리 구성에서는 스토리지 컨트롤러가 패브릭 인터커넥트에 연결됩니다.
* 핵심 FlexPod 구성 요소 사이에 추가 장비를 인라인으로 배치할 수 없습니다.
* Cisco Nexus 3000/9000 시리즈 스위치를 NetApp 스토리지 컨트롤러에 연결하려면 가상 포트 채널(vPC)이 필요합니다.
* 반드시 필요한 것은 아니지만 환경 전체에서 점보 프레임 지원을 사용하도록 설정하는 것이 좋습니다.




== NetApp E-Series를 사용하는 FlexPod Express의 연결 요구사항

FlexPod Express와 E-Series의 연결 요구 사항은 다음과 같습니다.

* E-Series 스토리지 컨트롤러는 패브릭 인터커넥트에 직접 연결해야 합니다.
* 핵심 FlexPod 구성 요소 사이에 추가 장비를 인라인으로 설치해서는 안 됩니다.
* 패브릭 인터커넥트와 이더넷 스위치 사이에는 vPC가 필요합니다.




== FlexPod Express와 NetApp AFF의 연결 요구 사항

FlexPod Express와 NetApp AFF의 연결 요구 사항은 다음과 같습니다.

* NetApp AFF 스토리지 컨트롤러는 Cisco Nexus 스위치에 직접 연결해야 합니다. 단, Cisco UCS 관리 구성에서는 스토리지 컨트롤러가 패브릭 인터커넥트에 연결됩니다.
* 핵심 FlexPod 구성 요소 사이에 추가 장비를 인라인으로 배치할 수 없습니다.
* Cisco Nexus 3000/9000 시리즈 스위치를 NetApp 스토리지 컨트롤러에 연결하려면 가상 포트 채널(vPC)이 필요합니다.
* 반드시 필요한 것은 아니지만 환경 전체에서 점보 프레임 지원을 사용하도록 설정하는 것이 좋습니다.

