---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp 스토리지 컨트롤러는 FlexPod Express 아키텍처에서 부팅 및 애플리케이션 데이터 저장을 위한 스토리지 기반을 제공합니다. 이 섹션에서는 FlexPod Express 아키텍처에서 사용할 수 있는 다양한 NetApp 스토리지 옵션을 나열합니다. 
---
= NetApp 구성 요소
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp 스토리지 컨트롤러는 부팅 및 애플리케이션 데이터 스토리지를 위한 FlexPod Express 아키텍처의 스토리지 기반을 제공합니다. 이 섹션에는 FlexPod 익스프레스 아키텍처의 다양한 NetApp 옵션이 나와 있습니다.



[[netapp-storage-controller-options]]
== NetApp 스토리지 컨트롤러 옵션

FlexPod Express 아키텍처에서는 이중화된 AFF, ASA 또는 FAS 시리즈 컨트롤러가 필요합니다. 이러한 컨트롤러는 ONTAP 소프트웨어를 실행합니다. 스토리지 컨트롤러를 주문할 때 원하는 소프트웨어 버전을 컨트롤러에 미리 설치할 수 있습니다. ONTAP의 경우, 클러스터는 한 쌍의 클러스터 인터커넥트 스위치를 사용하거나 스위치가 없는 클러스터 구성으로 배포할 수 있습니다.


NOTE: 스위치가 없는 클러스터 구성은 2노드 구성에서만 지원됩니다. 클러스터 인터커넥트 스위치는 4개 이상의 노드가 있는 구성에 필요하며 2노드 구성의 경우 선택 사항입니다.

선택한 스토리지 플랫폼에 따라 다양한 옵션과 구성이 가능합니다. 이러한 추가 구성 요소에 대한 자세한 내용은 영업 담당자에게 문의하십시오.

아래 표에 나열된 컨트롤러 제품군은 Cisco Nexus 스위치와의 연결이 원활하므로 FlexPod 솔루션에 사용하기에 적합합니다. 각 컨트롤러 모델의 구체적인 호환성 정보는 http://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]을 참조하십시오.

|===
| NetApp 엔트리 레벨 스토리지 제품군(FlexPod Express용) | 모델 | 기술 사양 


.2+| AFF A 시리즈 | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A 시리즈 문서"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C-Series 문서"] 


.2+| ASA A-Series | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA 문서"] 


| A30 


| ASA C-Series | C30 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 문서"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== 기능과 이점을 제공합니다

내장 디스크 쉘프가 없는 스토리지 컨트롤러에는 최소 하나의 NetApp 디스크 쉘프가 필요합니다. 선택한 NetApp 쉘프 유형에 따라 해당 쉘프에서 사용할 수 있는 드라이브 유형이 결정됩니다.


NOTE: 모든 디스크 쉘프와 디스크 부품 번호는 세일즈 담당자에게 문의하십시오.

다음 표에는 FlexPod Express용 NetApp 디스크 쉘프 옵션과 해당 기술 사양에 대한 링크가 나열되어 있습니다.

디스크 쉘프에 지원되는 드라이브 목록을 확인하려면 link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe를 참조하십시오"^]로 이동하여 *Products > Storage > Shelves* 에서 *ONTAP (AFF, ASA, FAS)* 를 선택하고, 사용 중인 ONTAP 버전을 선택한 다음, 쉘프 유형(예: *DS212C*)을 선택하고 *Show Results* 를 클릭합니다. *Supported Drives* 를 클릭하면 특정 ONTAP 버전 및 디스크 쉘프에서 지원되는 드라이브를 확인할 수 있습니다.

|===
| 디스크 쉘프 | 기술 사양 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["디스크 쉘프 및 저장 매체"] 


| DS224C 


| DS460C 


| NS224 


| NS224 w/NSM100B 
|===


[[netapp-software-licensing-options]]
== NetApp 소프트웨어 라이센스 옵션

다음 표는 NetApp 소프트웨어 라이선스 옵션을 보여줍니다.

|===
| NetApp 소프트웨어 라이센스 | 기술 사양 


| AFF 및 FAS용 ONTAP One .2+| 라이센스 정보에 대한 자세한 내용은 NetApp 세일즈 팀에 문의하십시오. 


| ASA용 ONTAP One for SAN 
|===
NetApp 소프트웨어 라이선스에 대한 자세한 내용은 다음 링크를 참조하십시오: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp 소프트웨어 라이센스"^].



[[netapp-support-licensing-options]]
== NetApp 지원 라이센스 옵션

SupportEdge Premium 라이센스는 필수이며, 이러한 라이센스의 부품 번호는 FlexPod Express 설계에서 선택한 옵션에 따라 달라집니다.

다음 표는 NetApp AFF, ASA 및 FAS 스토리지 시스템에 대한 NetApp 지원 라이선스 옵션을 나열합니다.

|===
| NetApp Support 라이센스 | 기술 사양 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===