---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_introduction.html 
keywords: flexpod, fabricpool, inactive, data, tiering, amazon, aws, s3 
summary: 이 기술 보고서에서는 NetApp과 Cisco의 FlexPod 통합 인프라 아키텍처를 기반으로 NetApp ONTAP의 FabricPool 데이터 계층화 기능을 검토합니다. 
---
= TR-4801: FabricPool를 지원하는 FlexPod - Amazon AWS S3에 대한 비활성 데이터 계층화
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Scott Kovacs, NetApp을 참조하십시오

플래시 스토리지의 가격이 계속 하락하고 있기 때문에 이전에 플래시 스토리지로 적합하지 않은 워크로드 및 애플리케이션에 사용할 수 있습니다. 그러나 스토리지 투자를 가장 효율적으로 활용하는 것은 IT 관리자에게 여전히 매우 중요합니다. IT 부서는 예산을 거의 또는 전혀 사용하지 않고 고성능 서비스를 제공해야 하는 지속적인 압박을 지속적으로 수행하고 있습니다. 이러한 요구사항을 해결하기 위해 NetApp FabricPool을 사용하면 자주 사용하지 않는 데이터를 값비싼 온프레미스 플래시 스토리지에서 퍼블릭 클라우드의 보다 비용 효율적인 스토리지 계층으로 이동하여 클라우드의 경제성을 활용할 수 있습니다. 자주 액세스하지 않는 데이터를 클라우드로 이동하면 AFF 또는 FAS 시스템에서 중요한 플래시 스토리지 공간을 확보하여 비즈니스 크리티컬 워크로드에 고성능 플래시 계층에 더 많은 용량을 제공할 수 있습니다.

이 기술 보고서에서는 NetApp과 Cisco의 FlexPod 통합 인프라 아키텍처를 기반으로 NetApp ONTAP의 FabricPool 데이터 계층화 기능을 검토합니다. 이 기술 보고서에서 설명된 개념을 충분히 활용하려면 FlexPod 데이터 센터 통합 인프라 아키텍처 및 ONTAP 스토리지 소프트웨어에 대해 잘 알고 있어야 합니다. FlexPod과 ONTAP에 대한 친숙도를 기반으로 FabricPool의 작동 방식 및 사내 플래시 스토리지를 더욱 효율적으로 사용하는 방법에 대해 설명합니다. 이 보고서의 내용 대부분은 에서 자세히 다룹니다 https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598 FabricPool 모범 사례"^] 및 기타 ONTAP 제품 설명서를 참조하십시오. FlexPod 인프라에 대한 콘텐츠가 압축되었으며 FabricPool의 모든 사용 사례에 대해서는 다루지 않습니다. 검사한 모든 기능과 개념은 ONTAP 9.6에서 사용할 수 있습니다.

FlexPod에 대한 자세한 내용은 에서 확인할 수 있습니다 https://www.netapp.com/pdf.html?item=/media/12424-tr4036.pdf["TR-4036 FlexPod 데이터 센터 기술 사양"^].
