---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_set_volume_tiering_minimum_cooling_days.html 
keywords: volume, tiering, minimum, cooling, days, set, auto, ontap, cli, snapshot 
summary: Tiering-Minimum-Cooling-Days 설정은 자동 또는 스냅샷 전용 정책을 사용하여 볼륨에 있는 비활성 데이터를 계층화하기에 앞서 경과해야 하는 일 수를 결정합니다. 
---
= 볼륨 계층화 최소 냉각 일 수 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


'Tiering-Minimum-Cooling-Days' 설정은 자동 또는 스냅샷 전용 정책을 사용하여 볼륨에 있는 비활성 데이터를 계층화하기에 앞서 경과해야 하는 일 수를 결정합니다.



== 자동

자동 계층화 정책의 기본 "계층화-최소-냉각-일" 설정은 31일입니다.

읽기 작업은 블록 온도를 고온으로 유지하기 때문에 이 값을 늘리면 계층화할 수 있는 데이터의 양이 줄어들고 성능 계층에 보관되는 데이터의 양이 증가할 수 있습니다.

이 값을 기본값인 31일에서 줄이려면 콜드 으로 표시되기 전에 데이터가 더 이상 활성 상태가 아니어야 합니다. 예를 들어, 여러 날 워크로드가 7일에 상당한 수의 쓰기를 수행할 것으로 예상되는 경우 볼륨의 '계층화-최소-냉각-일' 설정을 8일 이내에 설정해야 합니다.


NOTE: 오브젝트 스토리지는 파일 또는 블록 스토리지와 같은 트랜잭션 중심 스토리지가 아닙니다. 지나치게 공격적인 최소 냉각 일 수를 사용해 볼륨에 객체로 저장된 파일을 변경하면 새 오브젝트가 작성되고 기존 오브젝트가 조각화되고 스토리지 비효율성이 부가될 수 있습니다.



== 스냅샷 전용

스냅샷 전용 계층화 정책의 기본 '계층화-최소-냉각-일' 설정은 2일입니다. 최소 2일이 지나면 백그라운드 프로세스가 추가 시간을 제공하여 스토리지 효율성을 최대화하고 일상적인 데이터 보호 프로세스에서 클라우드 계층에서 데이터를 읽을 필요가 없도록 합니다.



== ONTAP CLI를 참조하십시오

ONTAP CLI를 사용하여 볼륨의 "Tiering-Minimum-Cooling-Days" 설정을 변경하려면 다음 명령을 실행합니다.

....
volume modify -vserver <svm_name> -volume <volume_name> -tiering-minimum-cooling-days <2-63>
....
고급 권한 수준이 필요합니다.


NOTE: 계층화 정책을 자동 및 스냅샷 전용 간에 또는 그 반대로 변경하면 성능 계층에서 블록의 비활성 기간이 재설정됩니다. 예를 들어, 20일 동안 비활성 상태인 성능 계층의 데이터와 함께 자동 볼륨 계층화 정책을 사용하는 볼륨은 계층화 정책이 스냅샷 전용으로 설정된 경우 성능 계층 데이터 비활성 상태가 0일로 재설정됩니다.
