---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-insights_use_cases.html 
keywords: target, cases, audience, cloud, insights, flexpod, ontap 
summary: 이 솔루션이 적용되는 대상 및 사례가 이 섹션에 나와 있습니다. 
---
= 사용 사례
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


이 솔루션은 다음과 같은 사용 사례에 적용됩니다.

* FlexPod 솔루션의 일부로 구축된 ONTAP 스토리지 시스템에서 다양한 리소스와 사용률을 모니터링하려는 조직
* AFF 또는 FAS 시스템을 통해 FlexPod 솔루션에서 발생하는 문제의 해결 시간을 단축하고 문제를 해결하려는 조직
* 비용 최적화 예상에 관심이 있는 조직(예: 낭비되는 리소스에 대한 자세한 정보와 FlexPod를 포함한 ONTAP 환경에서 비용 절감을 실현할 수 있는 맞춤형 대시보드 포함)




== 대상

이 솔루션의 대상 고객은 다음과 같은 그룹을 포함합니다.

* IT 경영진 및 비용 최적화 및 비즈니스 연속성 관련 담당자
* 데이터 센터 또는 하이브리드 클라우드 설계 및 관리에 관심이 있는 솔루션 설계자
* 문제 해결 및 인시던트 해결을 담당하는 기술 지원 엔지니어


계획, 문제 해결, 유지 관리 및 비즈니스 연속성 보장을 지원하는 데 사용할 수 있는 여러 가지 유용한 데이터 유형을 제공하도록 Cloud Insights를 구성할 수 있습니다. Cloud Insights로 FlexPod 데이터 센터 솔루션을 모니터링하고 집계된 데이터를 쉽게 파악할 수 있는 맞춤형 대시보드에 제공합니다. 구축 환경의 리소스를 수요 증가에 맞게 확장할 필요가 있는 시기를 예측할 수 있을 뿐만 아니라 시스템 내에서 문제를 일으키는 특정 애플리케이션 또는 스토리지 볼륨을 식별할 수도 있습니다. 이를 통해 모니터링 중인 인프라를 예측 가능하고 기대치에 따라 수행할 수 있으므로 조직에서 정의된 SLA를 이행하고 필요에 따라 인프라를 확장할 수 있으므로 낭비와 추가 비용이 발생하지 않습니다.
