---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-conclusion.html 
keywords: conclusion 
summary: 하이브리드 클라우드 구축은 대부분의 의료 조직에서 언제든지 데이터 가용성을 제공하는 데 목표를 두고 있습니다. 이 솔루션에서는 Cloud Volumes ONTAP 기반의 FlexPod 하이브리드 클라우드 솔루션을 구축하고, NetApp SnapMirror 복제 기술을 활용하여 일부 사용 사례를 검증함으로써 의료 애플리케이션과 워크로드를 백업 및 복구했습니다. 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-solution-validation.html["이전: 솔루션 검증."]

[role="lead"]
하이브리드 클라우드 구축은 대부분의 의료 조직에서 언제든지 데이터 가용성을 제공하는 데 목표를 두고 있습니다. 이 솔루션에서는 Cloud Volumes ONTAP 기반의 FlexPod 하이브리드 클라우드 솔루션을 구축하고, NetApp SnapMirror 복제 기술을 활용하여 일부 사용 사례를 검증함으로써 의료 애플리케이션과 워크로드를 백업 및 복구했습니다.

FlexPod는 Cisco와 NetApp의 전략적 파트너십을 통해 엄격한 테스트와 검증을 거친 통합 인프라로서 예측 가능한 낮은 지연 시간의 시스템 성능과 고가용성을 제공하도록 설계되었습니다. 이 접근 방식은 EHR 시스템의 사용자에게 높은 편안함 수준을 제공하며 궁극적으로는 최상의 응답 시간을 제공합니다.

온프레미스 데이터 센터에서 NetApp 스토리지 기능을 실행하는 것처럼 NetApp을 사용하면 클라우드에서 EHR 운영, 재해 복구, 백업 또는 계층화를 실행할 수 있습니다. NetApp Cloud Volumes ONTAP을 통해 NetApp은 클라우드에서 EHR을 효과적으로 실행하는 데 필요한 엔터프라이즈급 기능과 성능을 제공합니다. NetApp 클라우드 옵션은 iSCSI를 통한 블록 오버와 NFS 또는 SMB를 통한 파일 오버를 제공합니다.

이 솔루션은 의료 조직의 요구사항을 충족하여 디지털 혁신을 위한 조치를 취할 수 있도록 합니다. 또한 애플리케이션 및 워크로드를 효율적으로 관리하는 데도 도움이 됩니다.

link:fhc-cvoe-where-to-find-additional-information.html["다음: 추가 정보를 찾을 위치."]
