---
sidebar: sidebar 
permalink: hybrid-cloud/flexpod-rho-cvo-conclusion.html 
keywords: conclusion 
summary: 이 솔루션에서는 NetApp Astra 포트폴리오를 사용하여 FlexPod 및 AWS에서 실행되는 컨테이너식 애플리케이션에 대한 보호 계획을 구현했습니다. NetApp Astra Control Center 및 Astra Trident와 Cloud Volumes ONTAP, Red Hat OpenShift 및 FlexPod 인프라와 함께 이 솔루션의 핵심 구성요소를 구성했습니다. 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-rho-cvo-application-recovery-with-remote-backups.html["이전: 원격 백업을 사용한 애플리케이션 복구."]

이 솔루션에서는 NetApp Astra 포트폴리오를 사용하여 FlexPod 및 AWS에서 실행되는 컨테이너식 애플리케이션에 대한 보호 계획을 구현했습니다. NetApp Astra Control Center 및 Astra Trident와 Cloud Volumes ONTAP, Red Hat OpenShift 및 FlexPod 인프라와 함께 이 솔루션의 핵심 구성요소를 구성했습니다.

NetApp은 스냅샷 캡처를 통해 애플리케이션 보호를 입증했으며 전체 복사본 백업을 실행하여 클라우드 및 사내 환경에서 실행되는 서로 다른 K8s 클러스터 간에 애플리케이션을 복원합니다.

또한, K8s 클러스터 전체에 애플리케이션을 클론 복제함으로써 고객이 원하는 위치에서 원하는 K8s 클러스터로 애플리케이션을 마이그레이션할 수 있도록 했습니다.

FlexPod은 고객이 애플리케이션 및 비즈니스 제공 프로세스를 현대화할 수 있도록 지속적으로 진화해 왔습니다. FlexPod 고객은 이 솔루션을 사용하여 임시 또는 전체 시간 DR 계획을 위한 위치로 퍼블릭 클라우드를 사용하는 클라우드 네이티브 애플리케이션에 대한 BCDR 계획을 자신 있게 구축하는 동시에 솔루션 비용을 절감할 수 있습니다.

Astra Control을 사용하면 클러스터의 위치에 관계없이 전체 애플리케이션과 함께 Kubernetes 클러스터 간에 데이터를 이동할 수 있습니다. 또한 클라우드 네이티브 애플리케이션을 더 빠르게 구축, 운영, 보호할 수 있습니다.



== 문제 해결

문제 해결 지침은 을 참조하십시오 https://docs.netapp.com/us-en/astra-control-center/support/troubleshooting-acc.html["온라인 설명서"^].



== 추가 정보를 찾을 수 있는 위치

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹 사이트를 검토하십시오.

* FlexPod 홈 페이지
+
https://www.flexpod.com["https://www.flexpod.com"^]

* FlexPod용 Cisco Validated Design 및 구축 가이드
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* Ansible을 사용하여 VMware용 코드로 인프라를 포함하는 FlexPod 구축
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html#AnsibleAutomationWorkflowandSolutionDeployment"^]

* Ansible을 사용한 Red Hat OpenShift 베어 메탈 의 코드로서 인프라를 포함하는 FlexPod 구축
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_iac_redhat_openshift.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_iac_redhat_openshift.html"^]

* Cisco UCS 하드웨어 및 소프트웨어 상호 운용성 툴
+
https://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Cisco Intersight 데이터시트
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* NetApp Astra 문서
+
https://docs.netapp.com/us-en/astra-control-center/index.html["https://docs.netapp.com/us-en/astra-control-center/index.html"^]

* NetApp Astra Control Center를 참조하십시오
+
https://docs.netapp.com/us-en/astra-control-center/index.html["https://docs.netapp.com/us-en/astra-control-center/index.html"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/trident/index.html["https://docs.netapp.com/us-en/trident/index.html"^]

* NetApp 클라우드 관리자
+
https://docs.netapp.com/us-en/occm/concept_overview.html["https://docs.netapp.com/us-en/occm/concept_overview.html"^]

* NetApp Cloud Volumes ONTAP를 참조하십시오
+
https://docs.netapp.com/us-en/occm/task_getting_started_aws.html["https://docs.netapp.com/us-en/occm/task_getting_started_aws.html"^]

* Red Hat OpenShift
+
https://www.openshift.com/["https://www.openshift.com/"^]

* NetApp 상호 운용성 매트릭스 툴
+
http://support.netapp.com/matrix/["http://support.netapp.com/matrix/"^]





== 버전 기록

|===
| 버전 | 날짜 | 문서 버전 기록 


| 버전 1.0 | 2022년 7월 | ACC 22.04.0 해제 
|===