---
sidebar: sidebar 
permalink: hybrid-cloud/gcp-ncvo-conclusion.html 
keywords: conclusion 
summary: 이 솔루션에서는 Cisco Intersight Cloud Orchestrator를 기반으로 하는 퍼블릭 클라우드를 통해 DR 솔루션을 구축하는 데 NetApp Cloud Data Service, Cloud Volumes ONTAP 및 FlexPod Datacenter 인프라가 사용되었습니다. FlexPod 솔루션은 고객이 애플리케이션 및 비즈니스 제공 프로세스를 현대화할 수 있도록 지속적으로 진화해 왔습니다. 이 솔루션을 사용하면 DR 솔루션 비용을 낮게 유지하면서 임시 또는 전체 시간 DR 계획을 위한 전환 위치로 퍼블릭 클라우드에 BCDR 계획을 수립할 수 있습니다. 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:gcp-ncvo-solution-validation.html["이전: 솔루션 검증."]

[role="lead"]
이 솔루션에서는 Cisco Intersight Cloud Orchestrator를 기반으로 하는 퍼블릭 클라우드를 통해 DR 솔루션을 구축하는 데 NetApp Cloud Data Service, Cloud Volumes ONTAP 및 FlexPod Datacenter 인프라가 사용되었습니다. FlexPod 솔루션은 고객이 애플리케이션 및 비즈니스 제공 프로세스를 현대화할 수 있도록 지속적으로 진화해 왔습니다. 이 솔루션을 사용하면 DR 솔루션 비용을 낮게 유지하면서 임시 또는 전체 시간 DR 계획을 위한 전환 위치로 퍼블릭 클라우드에 BCDR 계획을 수립할 수 있습니다.

사내 FlexPod와 NetApp Cloud Volumes ONTAP 간 데이터 복제는 검증된 SnapMirror 기술을 통해 처리되었지만, 데이터 이동성 요구사항에 맞춰 Cloud Sync와 같은 다른 NetApp 데이터 전송 및 동기화 툴을 선택할 수도 있습니다. TLS/AES 기반의 내장 암호화 기술로 전송 중인 데이터의 보안

애플리케이션에 대한 임시 DR 계획이 있거나 비즈니스에 대한 전체 재해 복구 계획이 있는 경우 이 솔루션에 사용되는 제품 포트폴리오는 규모에 따라 두 가지 요구 사항을 모두 충족할 수 있습니다. Cisco Intersight Workflow Orchestrator를 기반으로 하므로 사전 구축된 워크플로우를 통해 프로세스를 재구성할 필요가 없으며 BCDR 계획의 구현 속도를 높일 수 있습니다.

이 솔루션을 사용하면 Cisco Intersight Cloud Orchestrator에서 제공하는 자동화 및 오케스트레이션을 통해 하이브리드 클라우드 전반에서 FlexPod 온프레미스 및 데이터 복제를 매우 쉽고 편리하게 관리할 수 있습니다.



== 추가 정보를 찾을 수 있는 위치

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹 사이트를 검토하십시오.



=== GitHub를 참조하십시오

* 모든 Terraform 설정이 사용됩니다
+
https://github.com/NetApp-Automation/FlexPod-hybrid-cloud-for-GCP-with-Intersight-and-CVO["https://github.com/NetApp-Automation/FlexPod-hybrid-cloud-for-GCP-with-Intersight-and-CVO"^]

* 워크플로 가져오기를 위한 JSON 파일
+
https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows["https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows"^]





=== Cisco Intersight를 참조하십시오

* Cisco Intersight 도움말 센터
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* Cisco Intersight Cloud Orchestrator 설명서:
+
https://intersight.com/help/saas/features/orchestration/configure["https://intersight.com/help/saas/features/orchestration/configure#intersight_cloud_orchestrator"^]

* HiashCorp Terraform 문서용 Cisco Intersight 서비스
+
https://intersight.com/help/saas/features/terraform_cloud/admin["https://intersight.com/help/saas/features/terraform_cloud/admin"^]

* Cisco Intersight 데이터시트
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html"^]

* Cisco Intersight Cloud Orchestrator 데이터 시트
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html"^]

* HiashCorp Terraform Data Sheet를 위한 Cisco Intersight 서비스
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html"^]





=== FlexPod

* FlexPod 홈 페이지
+
https://www.flexpod.com["https://www.flexpod.com"^]

* FlexPod용 Cisco Validated Design 및 구축 가이드
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["UCS 관리 모드, VMware vSphere 7.0 U2 및 NetApp ONTAP 9.9에서 Cisco UCS 4.2(1)가 지원되는 FlexPod 데이터 센터 설계 가이드"^]

* Cisco UCS X-Series 및 FlexPod 데이터 센터
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]





=== 상호 운용성

* NetApp 상호 운용성 매트릭스 툴
+
http://support.netapp.com/matrix/["http://support.netapp.com/matrix/"^]

* Cisco UCS 하드웨어 및 소프트웨어 상호 운용성 툴
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* VMware 호환성 가이드 를 참조하십시오
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





=== NetApp Cloud Volumes ONTAP 참조 문서

* NetApp 클라우드 관리자
+
https://docs.netapp.com/us-en/occm/concept_overview.html["https://docs.netapp.com/us-en/occm/concept_overview.html"^]

* Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html[]

* Cloud Volumes ONTAP TCO 계산기
+
https://cloud.netapp.com/google-cloud-calculator[]

* Cloud Volumes ONTAP Sizer
+
https://cloud.netapp.com/cvo-sizer["https://cloud.netapp.com/cvo-sizer"^]

* 클라우드 평가 툴
+
https://cloud.netapp.com/assessments[]

* NetApp 하이브리드 클라우드
+
https://cloud.netapp.com/hybrid-cloud[]

* Cloud Manager API 설명서
+
https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html["https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html"^]





=== 문제 해결

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)["https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)"^]



=== Terraform(Terraform

* Terraform 클라우드
+
https://www.terraform.io/cloud["https://www.terraform.io/cloud"^]

* Terraform 문서
+
https://www.terraform.io/docs/["https://www.terraform.io/docs/"^]

* NetApp Cloud Manager 레지스트리
+
https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates["https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates"^]





=== GCP

* GCP용 ONTAP 고가용성
+
https://cloud.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick["https://cloud.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick"^]

* GCP 페르쿼트
+
https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6["https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6"^]


