---
sidebar: sidebar 
permalink: flexpod-dc/fpd-cisco-vsphere-design.html 
keywords: flexpod, cisco, data, center, vmware, vsphere, 
summary: 이 문서에서는 Cisco 및 NetApp 기술을 공유 클라우드 인프라로 구축하기 위한 검증된 접근 방식인 Cisco 및 NetApp FlexPod 솔루션에 대해 설명합니다. 
---
= VMware vSphere 6.7 U1, Cisco UCS 4세대 패브릭 및 NetApp AFF A-Series를 지원하는 FlexPod 데이터 센터 - 설계
:allow-uri-read: 


John George, Cisco Sree Lakshmi Lanka, NetApp

[role="lead"]
이 문서에서는 Cisco 및 NetApp 기술을 공유 클라우드 인프라로 구축하기 위한 검증된 접근 방식인 Cisco 및 NetApp FlexPod 솔루션에 대해 설명합니다. 이 검증된 설계는 FlexPod에서 엔터프라이즈급 데이터 센터에서 가장 많이 사용되는 가상화 플랫폼인 VMware vSphere를 구축하기 위한 프레임워크를 제공합니다.

FlexPod은 광범위한 엔터프라이즈 워크로드 및 사용 사례를 지원하는 업계 최고의 통합 인프라입니다. 이 솔루션을 통해 고객은 통합 인프라에 VMware vSphere 기반 프라이빗 클라우드를 빠르고 안정적으로 구축할 수 있습니다.

권장 솔루션 아키텍처는 Cisco UCS(Cisco Unified Computing System) 기반 위에 구축되어 Cisco UCS B-Series 블레이드 및 C-Series 랙 서버, Cisco UCS 6454 Fabric Interconnect, Cisco Nexus 9000 시리즈 스위치, Cisco MDS 파이버 채널 스위치 등 Cisco UCS 하드웨어 플랫폼을 지원합니다. 및 NetApp All Flash Series 스토리지 어레이를 모두 활용할 수 있습니다. 또한 스토리지 활용을 최적화하고 프라이빗 클라우드를 지원하는 여러 가지 새로운 기능을 제공하는 VMware vSphere 6.7 Update 1이 포함되어 있습니다.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_vmware_netappaffa_design.html["VMware vSphere 6.7 U1, Cisco UCS 4세대 패브릭 및 NetApp AFF A-Series를 지원하는 FlexPod 데이터 센터 - 설계"^]
