---
sidebar: sidebar 
permalink: security/flexpod-fips-overview-of-fips-140-2.html 
keywords: fips 120-2, cryptographic module, security level, 
summary: FIPS 140-2는 컴퓨터 및 통신 시스템의 중요한 정보를 보호하는 보안 시스템 내에서 사용되는 암호화 모듈에 대한 보안 요구 사항을 지정합니다. 
---
= FIPS 140-2 개요
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-cybersecurity-threats-in-healthcare.html["이전: 의료 분야의 사이버 보안 위협"]

https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf["FIPS 140-2"^] 컴퓨터 및 통신 시스템의 중요한 정보를 보호하는 보안 시스템 내에서 사용되는 암호화 모듈에 대한 보안 요구 사항을 지정합니다. 암호화 모듈은 하드웨어, 소프트웨어, 펌웨어 또는 조합 세트여야 합니다. FIPS는 암호화 경계 내에 포함된 암호화 알고리즘, 키 생성 및 키 관리자에 적용됩니다. FIPS 140-2는 제품, 아키텍처, 데이터 또는 에코시스템이 아닌 암호화 모듈에 특히 적용된다는 점을 이해하는 것이 중요합니다. 이 문서의 뒷부분에 나오는 주요 용어로 정의된 암호화 모듈은 승인된 보안 기능을 구현하는 특정 구성 요소(하드웨어, 소프트웨어 및/또는 펌웨어)입니다. 또한 FIPS 140-2는 네 가지 레벨을 지정합니다. 승인된 암호화 알고리즘은 모든 수준에 공통적입니다. 각 보안 수준의 주요 요소 및 요구 사항은 다음과 같습니다.

* * 보안 수준 1 *
+
** 암호화 모듈에 대한 기본 보안 요구 사항을 지정합니다(하나 이상의 승인된 알고리즘 또는 보안 기능이 필요함).
** 운영 등급 구성 요소의 기본 요구 사항을 초과하는 수준 1에는 지정된 물리적 보안 메커니즘이 필요하지 않습니다.


* * 보안 수준 2 *
+
** 코팅 또는 봉인, 탈착식 커버 또는 암호화 모듈의 도어에 잠금 장치와 같은 변조 방지 솔루션을 사용하여 변조 증거에 대한 요구 사항을 추가하여 물리적 보안 메커니즘을 강화합니다.
** 최소한 역할 기반 액세스 제어(RBAC)가 필요하며, 이 경우 암호화 모듈은 운영자 또는 관리자의 권한을 인증하여 특정 역할을 수행하고 해당 기능 세트를 수행해야 합니다.


* * 보안 수준 3 *
+
** 레벨 2의 변조 가능한 요구 사항을 기반으로 암호화 모듈 내의 중요 보안 매개 변수(CSP)에 대한 추가 액세스를 방지합니다.
** 수준 3에 필요한 물리적 보안 메커니즘은 물리적 액세스 시도 또는 암호화 모듈의 사용 또는 수정 시도를 감지하고 이에 대응할 가능성이 높은 것을 목적으로 합니다. 암호화 모듈의 이동식 덮개가 열릴 때 모든 일반 텍스트 CSP를 제로화하는 강력한 인클로저, 변조 감지 및 응답 회로가 이러한 예에 포함될 수 있습니다.
** 레벨 2에 지정된 RBAC 메커니즘의 보안을 강화하기 위해 ID 기반 인증 메커니즘이 필요합니다. 암호화 모듈은 운영자의 ID를 인증하고 운영자가 역할을 사용하고 역할의 기능을 수행할 권한이 있는지 확인합니다.


* * 보안 수준 4 *
+
** FIPS 140-2의 최고 보안 수준.
** 물리적으로 보호되지 않는 환경에서 작업을 수행하는 데 가장 유용한 레벨입니다.
** 이 수준에서 물리적 보안 메커니즘은 물리적 액세스에서 승인되지 않은 시도를 감지하고 대응하는 책임을 지고 암호화 모듈에 대한 완벽한 보호를 제공하기 위한 것입니다.
** 암호화 모듈의 침투 또는 노출은 감지 가능성이 높으며 모든 비보안 또는 일반 텍스트 CSP의 즉각적인 제로로 이어질 수 있습니다.




link:flexpod-fips-control-plane-versus-data-plane.html["다음: 컨트롤 플레인 대 데이터 플레인"]
