---
sidebar: sidebar 
permalink: security/flexpod-fips-where-to-find-additional-information.html 
keywords:  
summary:  
---
= 감사의 말, 버전 기록 및 추가 정보를 찾을 수 있는 위치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-conclusion.html["이전: 결론."]

[role="lead"]
이 문서에 설명된 정보에 대한 자세한 내용은 다음 문서 및 웹 사이트를 참조하십시오.

* Cisco MDS 9000 제품군 NX-OS 보안 구성 가이드
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/sw/8_x/config/security/cisco_mds9000_security_config_guide_8x/configuring_fips.html#task_1188151[]

* Cisco Nexus 9000 시리즈 NX-OS 보안 구성 가이드, 릴리즈 9.3(x)
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/security/configuration/guide/b-cisco-nexus-9000-nx-os-security-configuration-guide-93x/m-configuring-fips.html[]

* NetApp 및 FIPS(Federal Information Processing Standard) 간행물 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* FIPS 140-2
+
https://fieldportal.netapp.com/content/902303[]

* NetApp ONTAP 9 강화 가이드
+
https://www.netapp.com/us/media/tr-4569.pdf[]

* NetApp 암호화 기능 가이드 를 참조하십시오
+
https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.pow-nve%2Fhome.html[]

* NVE 및 NAE 데이터시트
+
https://www.netapp.com/us/media/ds-3899.pdf[]

* NSE 데이터시트
+
https://www.netapp.com/us/media/ds-3213-en.pdf[]

* ONTAP 9 문서 센터
+
http://docs.netapp.com[]

* NetApp 및 FIPS(Federal Information Processing Standard) 간행물 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* Cisco 및 FIPS 140-2 규정 준수
+
https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html[]

* NetApp 암호화 보안 모듈
+
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2648.pdf[]

* 중대형 의료 조직을 위한 사이버 보안 사례
+
https://www.phe.gov/Preparedness/planning/405d/Documents/tech-vol2-508.pdf[]

* Cisco 및 CMVP(Cryptographic Module Validation Program)
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&Vendor=cisco&CertificateStatus=Active&ValidationYear=0[]

* NetApp 스토리지 암호화, NVMe 자체 암호화 드라이브, NetApp 볼륨 암호화 및 NetApp 애그리게이트 암호화
+
https://www.netapp.com/pdf.html?item=/media/17073-ds-3898.pdf[]

* NetApp 볼륨 암호화 및 NetApp 애그리게이트 암호화
+
https://www.netapp.com/pdf.html?item=/media/17070-ds-3899.pdf[]

* NetApp 스토리지 암호화
+
https://www.netapp.com/pdf.html?item=/media/7563-ds-3213-en.pdf[]

* 전자 건강 기록 시스템용 FlexPod
+
https://www.netapp.com/pdf.html?item=/media/22199-tr-4881.pdf[]

* Data Now:클라우드 연결 플래시 기술로 Epic EHR 환경의 성능 향상
+
https://www.netapp.com/media/10809-cloud-connected-flash-wp.pdf[]

* Epic EHR 인프라용 FlexPod Datacenter
+
https://www.netapp.com/pdf.html?item=/media/17061-ds-3683.pdf[]

* Epic EHR용 FlexPod 데이터 센터 구축 가이드 를 참조하십시오
+
https://www.netapp.com/media/10658-tr-4693.pdf[]

* MEDITECH 소프트웨어용 FlexPod 데이터 센터 인프라
+
https://www.netapp.com/media/8552-flexpod-for-meditech-software.pdf[]

* FlexPod 표준은 MEDITECH 소프트웨어로 확장됩니다
+
https://blog.netapp.com/the-flexpod-standard-extends-to-meditech-software/[]

* MEDITECH 방향 사이징 가이드용 FlexPod
+
https://www.netapp.com/pdf.html?item=/media/12429-tr4774.pdf[]

* 의료 영상 촬영용 FlexPod
+
https://www.netapp.com/media/19793-tr-4865.pdf[]

* 의료 부문의 AI
+
https://www.netapp.com/us/media/na-369.pdf[]

* 의료 분야의 혁신을 지원하는 FlexPod
+
https://flexpod.com/solutions/verticals/healthcare/[]

* Cisco와 NetApp의 FlexPod
+
https://flexpod.com/[]





== 감사의 말

* Abhinav Singh, NetApp 기술 마케팅 엔지니어
* Brian O는 NetApp의 솔루션 설계자 Healthcare(Epic) 입니다
* Brian Pruitt, NetApp 비즈니스 개발 매니저
* Arvind Ramakrishnan, NetApp 수석 솔루션 설계자
* Michael Hommer, NetApp의 FlexPod 글로벌 현장 CTO




== 버전 기록

|===
| 버전 | 날짜 | 문서 버전 기록 


| 버전 1.0 | 2021년 4월 | 최초 릴리스 
|===