---
sidebar: sidebar 
permalink: security/flexpod-fips-additional-flexpod-security-consideration.html 
keywords: security, cisco intersight, fpolicy, data at rest, data in flight, secure multitenancy 
summary: 'FlexPod 인프라는 모듈식, 컨버지드, 선택적으로 가상화, 확장 가능(스케일아웃 및 스케일업) 및 비용 효율적인 플랫폼입니다. FlexPod 플랫폼을 사용하면 컴퓨팅, 네트워크, 스토리지를 독립적으로 확장하여 애플리케이션 구축을 가속할 수 있습니다. 모듈식 아키텍처를 사용하므로 시스템 스케일아웃 및 업그레이드 작업 중에도 무중단으로 운영할 수 있습니다.' 
---
= 추가 FlexPod 보안 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-solution-benefits-of-flexpod-converged-infrastructure.html["이전: FlexPod 통합 인프라의 솔루션 이점"]

FlexPod 인프라는 모듈식, 컨버지드, 선택적으로 가상화, 확장 가능(스케일아웃 및 스케일업) 및 비용 효율적인 플랫폼입니다. FlexPod 플랫폼을 사용하면 컴퓨팅, 네트워크, 스토리지를 독립적으로 확장하여 애플리케이션 구축을 가속할 수 있습니다. 모듈식 아키텍처를 사용하므로 시스템 스케일아웃 및 업그레이드 작업 중에도 무중단으로 운영할 수 있습니다.

HIT 시스템의 여러 구성 요소는 SMB/CIFS, NFS, ext4 및 NTFS 파일 시스템에 데이터를 저장해야 합니다. 즉, 인프라가 NFS, CIFS 및 SAN 프로토콜을 통해 데이터 액세스를 제공해야 합니다. 단일 NetApp 스토리지 시스템에서 이러한 모든 프로토콜을 지원하여 프로토콜 관련 스토리지 시스템의 기존 관행을 제거할 수 있습니다. 또한, 단일 NetApp 스토리지 시스템은 EHR, PACS 또는 VNA, 유전체학, VDI 등 다양한 HIT 워크로드를 지원할 수 있습니다. 보장된 구성 가능한 성능 수준

HIT는 FlexPod 시스템에 배포되면 의료 산업에만 해당되는 여러 가지 이점을 제공합니다. 다음 목록은 이러한 이점에 대한 자세한 설명입니다.

* * FlexPod 보안 *. 보안은 FlexPod 시스템의 기초가 됩니다. 지난 몇 년 동안 랜섬웨어는 위협이 되었습니다. 랜섬웨어는 암호화 바이러스, 암호화를 사용하여 악성 소프트웨어를 빌드하는 일종의 맬웨어입니다. 이 맬웨어는 대칭 키 암호화와 비대칭 키 암호화를 모두 사용하여 피해자의 데이터를 잠그고 데이터 암호를 해독할 키를 제공하는 대가로 금전을 요구합니다. FlexPod 솔루션이 랜섬웨어와 같은 위협을 완화하는 방법을 알아보려면 을 참조하십시오 https://www.netapp.com/us/media/tr-4802.pdf["TR-4802: 랜섬웨어에 대한 솔루션"^]. FlexPod 인프라 구성 요소도 포함되어 있습니다 https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf["FIPS 140-2를 준수합니다"^].
* Cisco Intersight. * Cisco Intersight는 혁신적인 클라우드 기반의 서비스형 관리 플랫폼으로, 전체 스택 FlexPod 관리 및 오케스트레이션을 위한 단일 창을 제공합니다. Intersight 플랫폼은 FIPS 140-2 보안 호환 암호화 모듈을 사용합니다. 플랫폼의 대역 외 관리 아키텍처는 HIPAA와 같은 일부 표준 또는 감사 범위를 벗어납니다. 네트워크에서 개인 식별 가능한 건강 정보는 Intersight 포털에 전송되지 않습니다.
* * NetApp FPolicy 기술. * 이름 파일 정책의 진화된 FPolicy는 NFS 또는 SMB/CIFS 프로토콜을 통한 파일 액세스를 모니터링하고 관리하기 위한 파일 액세스 알림 프레임워크입니다. 이 기술은 10년 이상 ONTAP 데이터 관리 소프트웨어의 일부였습니다. 랜섬웨어의 탐지에 유용합니다. 이 제로 트러스트 엔진은 ACL(액세스 제어 목록)의 사용 권한 외에 추가적인 보안 조치를 제공합니다. FPolicy는 두 가지 운영 모드, 즉 기본 및 외부 모드를 사용합니다.
+
** 기본 모드는 파일 확장명의 블랙리스트와 화이트리스팅을 모두 제공합니다.
** 외부 모드는 네이티브 모드와 동일한 기능을 제공하지만, ONTAP 시스템 외부에서 실행되는 FPolicy 서버와 SIEM(보안 정보 및 이벤트 관리) 시스템과도 통합됩니다. 랜섬웨어에 대항하는 방법에 대한 자세한 내용은 를 참조하십시오 https://blog.netapp.com/fighting-ransomware-tools["랜섬웨어에 대항하기: 3부 – 강력한 기본(무료) 툴인 ONTAP FPolicy"^] 블로그:


* * 저장된 데이터 *. ONTAP 9 이상에서는 FIPS 140-2를 준수하는 세 가지 유휴 데이터 암호화 솔루션이 있습니다.
+
** NSE는 자체 암호화 드라이브를 사용하는 하드웨어 솔루션입니다.
** NVE는 각 볼륨의 고유 키를 사용해 활성화된 모든 드라이브 유형의 모든 데이터 볼륨을 암호화할 수 있는 소프트웨어 솔루션입니다.
** NAE는 각 애그리게이트의 고유 키를 사용하여 활성화된 모든 드라이브 유형의 모든 데이터 볼륨을 암호화할 수 있는 소프트웨어 솔루션입니다.





NOTE: ONTAP 9.7부터 NAE와 NVE는 VE라는 이름의 NetApp NVE 라이센스 패키지가 설치된 경우 기본적으로 활성화됩니다.

* * 비행 중인 데이터 *. ONTAP 9.8부터 IPsec(인터넷 프로토콜 보안)은 클라이언트와 ONTAP SVM 사이의 모든 IP 트래픽에 엔드 투 엔드 암호화 지원을 제공합니다. 모든 IP 트래픽에 대한 IPsec 데이터 암호화에는 NFS, iSCSI 및 SMB/CIFS 프로토콜이 포함됩니다. IPsec은 iSCSI 트래픽에 대해 전송 중인 유일한 암호화 옵션을 제공합니다.
* * 하이브리드 멀티 클라우드 Data Fabric * 에서 엔드 투 엔드 데이터 암호화 데이터 복제 트래픽에 NSE 또는 NVE, CPE(Cluster 피어링 암호화)와 같은 유휴 데이터 암호화 기술을 사용하는 고객은 이제 ONTAP 9.8 이상으로 업그레이드하고 IPsec을 사용하여 하이브리드 멀티 클라우드 데이터 패브릭 전체에서 클라이언트와 스토리지 간의 엔드 투 엔드 암호화를 사용할 수 있습니다. ONTAP 9부터는 클러스터 차원의 제어 평면 인터페이스를 위해 FIPS 140-2 규정 준수 모드를 활성화할 수 있습니다. 기본적으로 FIPS 140-2 전용 모드는 비활성화되어 있습니다. ONTAP 9.6부터 CPE는 ONTAP SnapMirror, NetApp SnapVault 및 NetApp FlexCache 기술과 같은 데이터 복제 기능에 TLS 1.2 AES-256 GCM 암호화 지원을 제공합니다. 암호화는 두 클러스터 피어 간에 미리 공유된 키(PSK)를 통해 설정됩니다.
* * 보안 멀티 테넌시 *. 가상화된 서버 및 스토리지 공유 인프라의 증가하는 요구 사항을 지원하여 특히 데이터베이스 및 소프트웨어의 여러 인스턴스를 호스팅할 때 시설별 정보의 안전한 멀티 테넌시를 지원합니다.


link:flexpod-fips-conclusion.html["다음: 결론."]
