---
sidebar: sidebar 
permalink: security/flexpod-fips-flexpod-cisco-ucs-compute-and-fips-140-2.html 
keywords: compute, cisco, nist, compliance mode, fabric interconnect, fi, advanced malware protection 
summary: FlexPod 아키텍처는 FIPS 140-2를 준수하는 Cisco UCS 서버로 설계할 수 있습니다. 미국 S. NIST, Cisco UCS 서버는 FIPS 140-2 레벨 1 준수 모드에서 작동할 수 있습니다. 
---
= FlexPod Cisco UCS 컴퓨팅 및 FIPS 140-2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-control-plane-versus-data-plane.html["이전: 컨트롤 플레인 대 데이터 플레인"]

FlexPod 아키텍처는 FIPS 140-2를 준수하는 Cisco UCS 서버로 설계할 수 있습니다. 미국 S. NIST, Cisco UCS 서버는 FIPS 140-2 레벨 1 준수 모드에서 작동할 수 있습니다. FIPS 호환 Cisco 구성 요소의 전체 목록은 을 참조하십시오 https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html?flt0_general-table0=UCSM["Cisco의 FIPS 140 페이지"^]. Cisco UCS Manager는 FIPS 140-2 검증을 거쳤습니다.



== Cisco UCS 및 패브릭 인터커넥트

Cisco UCS Manager는 Cisco Fabric Interconnect(FI)에서 구축 및 실행됩니다.

Cisco UCS 및 FIPS 활성화 방법에 대한 자세한 내용은 를 참조하십시오 https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/release/notes/CiscoUCSManager-RN-3-2.html["Cisco UCS Manager 설명서"^].

각 패브릭 A 및 B의 Cisco 패브릭 인터커넥트에서 FIPS 모드를 활성화하려면 다음 명령을 실행합니다.

....
fp-health-fabric-A# connect local-mgmt
fp-health-fabric-A(local-mgmt)# enable fips-mode
FIPS mode is enabled
....

NOTE: Cisco UCS Manager 릴리즈 3.2(3)의 클러스터에서 Cisco UCS Manager 릴리즈 3.2(3) 이전 릴리즈의 FI로 FI를 교체하려면 교체 FI를 클러스터에 추가하기 전에 기존 FI에서 FIPS 모드(FIPS 모드 비활성화)를 비활성화하십시오. Cisco UCS Manager의 부팅 과정에서 클러스터가 구성되면 FIPS 모드가 자동으로 설정됩니다.

Cisco는 컴퓨팅 또는 애플리케이션 계층에서 구현할 수 있는 다음과 같은 주요 제품을 제공합니다.

* * 엔드포인트용 Cisco AMP(Advanced Malware Protection).* Microsoft Windows 및 Linux 운영 체제에서 지원되는 이 솔루션은 예방, 검색 및 응답 기능을 통합합니다. 이 보안 소프트웨어는 침입을 방지하고 진입 지점에서 맬웨어를 차단하며 파일 및 프로세스 활동을 지속적으로 모니터링 및 분석하여 일선 방어를 우회할 수 있는 위협을 신속하게 탐지, 억제 및 해결합니다. AMP의 MAP(Malicious Activity Protection) 구성 요소는 모든 엔드포인트 활동을 지속적으로 모니터링하고 엔드포인트에서 실행 중인 프로그램의 비정상적인 동작을 런타임 감지 및 차단합니다. 예를 들어, 엔드포인트 동작에 랜섬웨어가 표시되면 문제가 되는 프로세스가 종료되어 엔드포인트 암호화가 예방되고 공격이 중지됩니다.
* 이메일 보안을 위한 * AMP. * 이메일은 맬웨어를 유포하고 사이버 공격을 수행하는 주요 수단으로 자리 잡았습니다. 평균적으로 하루 동안 약 1,000억 개의 이메일이 교환되며, 이를 통해 공격자들은 사용자 시스템에 대한 탁월한 침투 벡터를 얻을 수 있습니다. 따라서 이 공격 라인을 방어하는 것이 절대적으로 중요합니다. AMP는 제로 데이 익스플로잇(zero-day exploit) 및 악성 첨부 파일에 숨겨진 악성 맬웨어와 같은 위협에 대한 이메일을 분석합니다. 또한 업계 최고의 URL 인텔리전스를 사용하여 악성 링크를 차단합니다. 스피어 피싱, 랜섬웨어 및 기타 정교한 공격에 대한 고급 보호 기능을 제공합니다.
* * NGIPS(Next-Generation Intrusion Prevention System). * Cisco firepower NGIPS는 데이터 센터에서 물리적 어플라이언스로 구축하거나 VMware(NGIPSv for VMware)에서 가상 어플라이언스로 구축할 수 있습니다. 이 고효율 침입 방지 시스템은 안정적인 성능과 낮은 총 소유 비용을 제공합니다. AMP, 애플리케이션 가시성 및 제어, URL 필터링 기능을 제공하기 위해 선택적 구독 라이센스로 위협 보호를 확장할 수 있습니다. 가상화된 NGIPS는 VM(가상 시스템) 간의 트래픽을 검사하고 리소스가 제한된 사이트에서 NGIPS 솔루션을 쉽게 배포 및 관리할 수 있도록 하여 물리적 자산과 가상 자산 모두의 보호를 강화합니다.


link:flexpod-fips-flexpod-cisco-networking-and-fips-140-2.html["다음으로, FlexPod Cisco 네트워킹 및 FIPS 140-2가 있습니다."]
