---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_design.html 
keywords: architecture, storage, layout, aggregates, database, disk, type, control, failover, hardware, aff 
summary: MEDITECH용 FlexPod의 아키텍처는 MEDITECH, Cisco 및 NetApp의 지침과 모든 규모의 MEDITECH 고객과 협업하는 파트너의 경험을 바탕으로 합니다. 이 아키텍처는 데이터 센터 전략, 조직의 규모, 시스템이 중앙 집중형, 분산 또는 멀티 테넌트 중 어디에 있는지에 따라 적응성이 뛰어나고 MEDITECH의 모범 사례를 적용합니다. 
---
= 설계
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


MEDITECH용 FlexPod의 아키텍처는 MEDITECH, Cisco 및 NetApp의 지침과 모든 규모의 MEDITECH 고객과 협업하는 파트너의 경험을 바탕으로 합니다. 이 아키텍처는 데이터 센터 전략, 조직의 규모, 시스템이 중앙 집중형, 분산 또는 멀티 테넌트 중 어디에 있는지에 따라 적응성이 뛰어나고 MEDITECH의 모범 사례를 적용합니다.

올바른 스토리지 아키텍처는 총 IOPS의 전체 크기에 따라 결정됩니다. 성능만 중요한 요소가 아니므로 추가 고객 요구사항을 기반으로 더 많은 노드 수를 사용할 수도 있습니다. NetApp 스토리지를 사용하면 요구사항의 변화에 따라 쉽고 중단 없이 클러스터를 확장할 수 있습니다. 또한 운영 중단 없이 클러스터에서 노드를 제거하여 장비를 용도 변경하거나 장비를 새로 고칠 수 있습니다.

NetApp ONTAP 스토리지 아키텍처의 이점은 다음과 같습니다.

* * 손쉬운 무중단 스케일업 및 스케일아웃 * ONTAP 무중단 운영을 사용하면 디스크와 노드를 업그레이드, 추가, 제거할 수 있습니다. 4개 노드로 시작한 후 6개 노드로 이동하거나 더 큰 컨트롤러로 중단 없이 업그레이드할 수 있습니다.
* * 스토리지 효율성 * 중복제거, NetApp FlexClone, 인라인 압축, 인라인 컴팩션, 씬 복제를 통해 총 용량 요구사항 감소 씬 프로비저닝 및 애그리게이트 중복제거. FlexClone 기능을 사용하면 거의 즉시 클론을 생성하여 백업 및 테스트 환경 업데이트를 지원할 수 있습니다. 이러한 클론은 변경된 경우에만 더 많은 스토리지를 사용합니다.
* * 재해 복구 섀도우 데이터베이스 서버. * 재해 복구 섀도우 데이터베이스 서버는 비즈니스 연속성 전략의 일부입니다(스토리지 읽기 전용 기능을 지원하고 스토리지 읽기/쓰기 인스턴스로 구성될 수 있음). 따라서 세 번째 스토리지 시스템의 배치 및 사이징은 일반적으로 운영 데이터베이스 스토리지 시스템과 동일합니다.
* * 데이터베이스 일관성(일부 고려 사항 필요) * 비즈니스 연속성과 관련하여 NetApp SnapMirror 백업 복사본을 사용하는 경우 을 참조하십시오 http://media.netapp.com/documents/tr-3446.pdf["TR-3446: SnapMirror 비동기 개요 및 모범 사례 가이드"^].




== 스토리지 레이아웃



=== MEDITECH 호스트용 전용 Aggregate

MEDITECH의 고성능 및 고가용성 요구 사항을 충족하기 위한 첫 번째 단계는 MEDITECH 환경의 스토리지 레이아웃을 적절하게 설계하여 MEDITECH 호스트 운영 워크로드를 전용 고성능 스토리지로 격리하는 것입니다.

MEDITECH 호스트의 프로그램, 사전 및 데이터 파일을 저장하기 위해 각 스토리지 컨트롤러에 하나의 전용 애그리게이트를 프로비저닝해야 합니다. 동일한 디스크를 사용하고 성능에 영향을 주는 다른 워크로드의 가능성을 없애기 위해 해당 애그리게이트에서 다른 스토리지는 프로비저닝되지 않습니다.


NOTE: 다른 MEDITECH 서버에 대해 용량 할당하는 스토리지는 MEDITECH 호스트에서 사용되는 LUN의 전용 애그리게이트에 배치해서는 안 됩니다. 다른 MEDITECH 서버의 스토리지를 별도의 Aggregate에 배치해야 합니다. 다른 MEDITECH 서버의 스토리지 요구 사항은 "하드웨어 구성 제안"(신규 구축) 및 "하드웨어 평가 작업"(기존 구축) 문서에서 확인할 수 있습니다. MEDITECH 시스템 통합자나 MEDITECH TAM(기술 계정 관리자)을 통해 MEDITECH에서 이러한 문서를 얻을 수 있습니다. NetApp 솔루션 엔지니어는 NetApp MEDITECH ISV(Independent Software Vendor) 팀과 협의하여 적절하고 완벽한 NetApp 스토리지 사이징 구성을 지원할 수 있습니다.



=== MEDITECH 호스트 워크로드를 모든 스토리지 컨트롤러에 균등하게 분산시킵니다

NetApp FAS 및 AFF 시스템은 하나 이상의 고가용성 쌍으로 구축됩니다. 각 스토리지 컨트롤러에 MEDITECH의 넓은 워크로드와 6.x 워크로드를 균등하게 배포하여 컴퓨팅, 네트워크 및 캐싱 리소스를 각 스토리지 컨트롤러에 적용하는 것이 좋습니다.

다음 지침에 따라 각 스토리지 컨트롤러에 MEDITECH 워크로드를 균등하게 분산시키십시오.

* 각 MEDITECH 호스트의 IOPS를 알고 있는 경우 각 컨트롤러가 MEDITECH 호스트에서 유사한 수의 IOPS를 서비스하는지 확인하여 MEDITECH의 넓은 워크로드와 6.x 워크로드를 모든 스토리지 컨트롤러에 균등하게 분산시킬 수 있습니다.
* 각 MEDITECH 호스트의 IOPS를 모르는 경우에도 MEDITECH의 드넓은 워크로드와 6.x 워크로드를 모든 스토리지 컨트롤러에 균등하게 분산시킬 수 있습니다. MEDITECH 호스트의 애그리게이트 용량이 모든 스토리지 컨트롤러에 균등하게 분산되는지 확인하여 이 작업을 완료합니다. 이렇게 하면 MEDITECH 호스트 전용으로 사용되는 모든 데이터 집마다 디스크 수가 동일합니다.
* 비슷한 디스크 유형과 동일한 RAID 그룹을 사용하여 워크로드를 균등하게 분산하기 위해 두 컨트롤러의 스토리지 애그리게이트를 만들 수 있습니다. 스토리지 애그리게이트를 생성하려면 NetApp 인증 통합업체에 문의하십시오.



NOTE: MEDITECH에 따르면 MEDITECH 시스템의 두 호스트는 나머지 호스트보다 높은 IOPS를 생성합니다. 이 두 호스트의 LUN은 별도의 스토리지 컨트롤러에 배치해야 합니다. 시스템을 배포하기 전에 MEDITECH 팀의 도움을 받아 이 두 호스트를 식별해야 합니다.



== 저장 장치 배치



=== MEDITECH 호스트용 데이터베이스 스토리지

MEDITECH 호스트의 데이터베이스 스토리지는 NetApp FAS 또는 AFF 시스템에서 블록 디바이스, 즉 LUN으로 제공됩니다. LUN은 일반적으로 Windows 운영 체제에 E 드라이브로 마운트됩니다.



=== 기타 스토리지

MEDITECH 호스트 운영 체제와 데이터베이스 애플리케이션은 일반적으로 스토리지에 상당한 양의 IOPS를 생성합니다. MEDITECH 호스트 VM 및 해당 VMDK 파일에 대한 스토리지 프로비저닝은 MEDITECH 성능 임계값을 충족하는 데 필요한 스토리지와는 독립적인 것으로 간주됩니다.

다른 MEDITECH 서버에 대해 프로비저닝된 스토리지는 MEDITECH 호스트가 사용하는 LUN의 전용 애그리게이트에 배치해서는 안 됩니다. 다른 MEDITECH 서버용 스토리지를 별도의 Aggregate에 배치합니다.



== 스토리지 컨트롤러 구성



=== 고가용성

컨트롤러 장애의 영향을 줄이고 스토리지 시스템의 무중단 업그레이드를 활성화하려면 고가용성 모드에서 컨트롤러를 사용하여 스토리지 시스템을 구성해야 합니다.

고가용성 컨트롤러 쌍 구성에서는 디스크 쉘프를 여러 경로를 통해 컨트롤러에 연결해야 합니다. 이 연결은 단일 경로 장애로부터 보호하여 스토리지 복원력을 높이고 컨트롤러 페일오버가 발생할 경우 성능 일관성을 개선합니다.



=== 스토리지 컨트롤러 페일오버 중 스토리지 성능

고가용성 쌍의 컨트롤러로 구성된 스토리지 시스템의 경우, 컨트롤러 장애가 발생할 가능성이 낮은 경우 파트너 컨트롤러가 장애가 발생한 컨트롤러의 스토리지 리소스 및 워크로드를 대신 처리합니다. 컨트롤러 장애가 있는 경우 고객과 상의하여 성능 요구사항을 충족하고 시스템을 적절하게 사이징하는 것이 중요합니다.



=== 하드웨어 지원 테이크오버

두 스토리지 컨트롤러 모두에서 하드웨어 지원 테이크오버 기능을 설정하는 것이 좋습니다.

하드웨어 지원 테이크오버는 스토리지 컨트롤러 페일오버 시간을 최소화하도록 설계되었습니다. 하나의 컨트롤러의 원격 LAN 모듈 또는 서비스 프로세서 모듈이 하트비트 시간 제한 트리거보다 빠르게 컨트롤러 장애에 대해 파트너에게 알릴 수 있으므로 장애 조치에 걸리는 시간이 줄어듭니다. 하드웨어 지원 테이크오버 기능은 고가용성 구성의 스토리지 컨트롤러에 대해 기본적으로 설정됩니다.

하드웨어 지원 테이크오버에 대한 자세한 내용은 를 참조하십시오 http://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"^].



=== 디스크 유형입니다

MEDITECH 워크로드의 낮은 읽기 지연 시간 요구사항을 지원하려면 MEDITECH 호스트 전용 AFF 시스템의 애그리게이트에 고성능 SSD를 사용하는 것이 좋습니다.



=== NetApp AFF를 참조하십시오

NetApp은 높은 처리량이 요구되는 MEDITECH 워크로드와 랜덤 데이터 액세스 패턴 및 짧은 지연 시간 요구사항을 해결하기 위해 고성능 AFF 어레이를 제공합니다. MEDITECH 워크로드의 경우 AFF 어레이는 HDD를 기반으로 하는 시스템에 비해 뛰어난 성능을 제공합니다. 플래시 기술과 엔터프라이즈 데이터 관리를 결합하면 성능, 가용성 및 스토리지 효율성이라는 세 가지 주요 영역에서 이점을 얻을 수 있습니다.



=== NetApp 지원 툴 및 서비스

NetApp은 완벽한 지원 툴 및 서비스 세트를 제공합니다. NetApp AutoSupport 툴은 하드웨어 장애나 시스템 구성 오류가 있는 경우 NetApp AFF/FAS 시스템에서 사용하도록 설정 및 구성해야 합니다. NetApp 지원 팀은 콜홈 경고를 통해 적시에 문제를 해결합니다. NetApp Active IQ는 NetApp 시스템의 AutoSupport 정보를 기반으로 예측 가능한 사전 통찰력을 제공하여 가용성, 효율성 및 성능을 향상하는 웹 기반 애플리케이션입니다.
