---
sidebar: sidebar 
permalink: healthcare/ehr-epic-performance_test_methodology.html 
keywords: test, methodology, generationio, tool, genio, storage, harware, software, vms 
summary: 'Epic은 GenationIO 툴(Genio)을 사용하여 스토리지를 운영 상태로 전환할 수 있는지 확인합니다. 이 테스트에서는 스토리지 한계를 시험하고, 요구 사항이 실패할 때까지 스토리지 컨트롤러의 여유 공간을 확인함으로써 성능에 초점을 맞춥니다.' 
---
= 테스트 방법론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 테스트 계획

Epic은 GenationIO 툴(Genio)을 사용하여 스토리지를 운영 상태로 전환할 수 있는지 확인합니다. 이 테스트에서는 스토리지 한계를 시험하고, 요구 사항이 실패할 때까지 스토리지 컨트롤러의 여유 공간을 확인함으로써 성능에 초점을 맞춥니다.

이 테스트는 중요 Epic 워크로드를 보호하기 위해 AQOS(Adaptive Quality of Service)를 사용할 뿐만 아니라 여유 공간을 확인하는 데 중점을 두었습니다. AFF A300 테스트의 경우 스토리지 컨트롤러의 I/O를 구동하는 데 Genio가 로드된 2대의 서버가 사용됩니다. AFF A700 스토리지 컨트롤러의 I/O를 구동하는 데 Genio가 로드된 서버 3대가 사용됩니다. 서버 성능 제한 때문에 서버 3대가 사용되고 AFF A700에는 서버 3대가 필요합니다.



== 테스트 환경



=== 하드웨어 및 소프트웨어

이 연구를 위해 Cisco UCS B200-M5S에서 실행되는 VMware ESXi 6.5에 Red Hat Linux 가상 머신(VM) 3개를 구성했습니다. 서버 측에서 16Gb FC를 사용하고 스토리지 측에서는 16Gb FC를 사용하여 AFF 스토리지 컨트롤러 노드와 Cisco MDS 시리즈 스위치를 연결했습니다. AFF A700 노드는 NetApp 케이블 연결 모범 사례에 따라 3.8TB SSD가 있는 하나의 DS2446 디스크 쉘프에 연결되었습니다.

아래 세 개의 표에는 Epic 성능 테스트 구성에 사용한 하드웨어 및 소프트웨어 구성요소가 나와 있습니다.

다음 표에는 Epic Test 하드웨어 및 소프트웨어 구성 요소가 나열되어 있습니다.

|===
| 하드웨어 및 소프트웨어 구성 요소 | 세부 정보 


| VM용 운영 체제입니다 | RHEL 7.4 VM 


| 서버 블레이드의 운영 체제 | VMware ESXi 6.5 


| 물리적 서버 | Cisco UCS B200 M5 x 3 


| 서버당 프로세서 수 | 20코어 Intel Xeon Gold 6148 2.4GHz 2개 


| 서버당 물리적 메모리 | 768GB 


| FC 네트워크 | 16Gb FC 및 다중 경로 


| FC HBA | Cisco UCS VIC 1340의 FC vHBA 


| 클러스터 관리용 전용 퍼블릭 1GbE 포트 | Intel 1350GbE 포트 2개 


| 16Gb FC 스위치 | Cisco MDS 9148s 


| 40GbE 스위치 | Cisco Nexus 9332 스위치 
|===
다음 표에는 NetApp AFF A700 및 AFF A300 스토리지 시스템 하드웨어 및 소프트웨어가 나와 있습니다.

|===
| 하드웨어 및 소프트웨어 구성 요소 | AFF A700 세부 정보 | AFF A300 세부 정보 


| 수행할 수 있습니다 | 고가용성(HA) 액티브-액티브 쌍으로 구성된 AFF A700 컨트롤러 | 고가용성(HA) 액티브-액티브 쌍으로 구성된 AFF A300 컨트롤러 


| ONTAP 버전입니다 | 9.4 | 9.5 


| 총 드라이브 수입니다 | 36 | 24 


| 드라이브 크기 | 3.8TB | 3.8TB 


| 드라이브 유형입니다 | SSD를 지원합니다 | SSD를 지원합니다 


| FC 타겟 포트 | 16Gb 포트 8개(노드당 4개) | 16Gb 포트 8개(노드당 4개) 


| 이더넷 포트 | 10Gb 포트 4개(노드당 2개) | 10Gb 포트 4개(노드당 2개) 


| 스토리지 가상 시스템(SVM) | 두 노드 애그리게이트에서 하나의 SVM | 두 노드 애그리게이트에서 하나의 SVM 


| 이더넷 논리 인터페이스(LIF) | 1Gb 관리 LIF 4개(노드당 2개 개별 VLAN에 연결) | 1Gb 관리 LIF 4개(노드당 2개 개별 VLAN에 연결) 


| FC LIF | 16Gb 데이터 LIF 4개 | 16Gb 데이터 LIF 4개 
|===
다음 표에는 NetApp AFF A700 및 AFF A300 스토리지 시스템 레이아웃이 나와 있습니다.

|===
| 스토리지 레이아웃 | AFF A700 세부 정보 | AFF A300 세부 정보 


| SVM | Epic 애플리케이션 데이터베이스를 위한 단일 SVM | Epic 애플리케이션 데이터베이스를 위한 단일 SVM 


| 애그리게이트 | 각각 20TB 2개 | 각각 30TB 2개 


| 운영 볼륨입니다 | RHEL VM당 342GB 볼륨 16개 | RHEL VM당 512GB 볼륨 16개 


| 운영 LUN입니다 | 307GB LUN 16개, 볼륨당 1개 | 460GB LUN 16개, 볼륨당 1개 


| 저널용 볼륨 | RHEL VM당 95Gb 볼륨 2개 | RHEL VM당 240GB 볼륨 2개 


| 저널용 LUN | 75Gb LUN 2개, 볼륨당 1개 | 볼륨당 하나씩 190Gb LUN 2개 
|===