---
sidebar: sidebar 
permalink: healthcare/ehr-epic-deploy_netapp_configuration.html 
keywords: configuration, ha, pair, configuration, storage, fc, protocol, flexpod, epic 
summary: 'Epic 소프트웨어 환경에 구축된 NetApp 스토리지는 고가용성(HA) 쌍 구성에서 스토리지 컨트롤러를 사용합니다. FC 프로토콜(FCP)을 통해 두 컨트롤러에서 Epic 데이터베이스 서버로 스토리지를 제공해야 합니다.' 
---
= NetApp 구성입니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Epic 소프트웨어 환경에 구축된 NetApp 스토리지는 고가용성(HA) 쌍 구성에서 스토리지 컨트롤러를 사용합니다. FC 프로토콜(FCP)을 통해 두 컨트롤러에서 Epic 데이터베이스 서버로 스토리지를 제공해야 합니다. 이 구성은 정상 작동 중에 두 컨트롤러의 스토리지를 모두 사용하여 애플리케이션 로드를 균등하게 분산합니다.

운영 워크로드를 고장 도메인으로 분리하기 위한 Epic 요구사항은 Epic All-Flash 레퍼런스 아키텍처 전략 핸드북에 자세히 설명되어 있습니다. 계속하기 전에 이 문서를 자세히 읽으십시오. ONTAP 노드는 별도의 스토리지 풀로 간주될 수 있습니다.



== ONTAP 구성

이 섹션에서는 관련 ONTAP 명령을 사용한 샘플 구축 및 프로비저닝 절차에 대해 설명합니다. NetApp에서는 HA 컨트롤러 쌍을 사용하는 NetApp의 권장 스토리지 레이아웃을 구현하기 위해 스토리지가 프로비저닝되는 방식을 중점적으로 소개합니다. ONTAP의 주요 이점 중 하나는 기존 HA 쌍을 중단하지 않고 스케일아웃하는 기능입니다.

EPIC는 스토리지 프레젠테이션 및 호스트측 스토리지 레이아웃을 비롯한 자세한 스토리지 성능 요구 사항 및 레이아웃 지침을 각 고객에게 제공합니다. EPIC는 다음과 같은 사용자 지정 문서를 제공합니다.

* 프리세일즈 과정에서 사이징에 사용되는 Epic 하드웨어 구성 가이드
* 구축 중에 LUN 및 볼륨 레이아웃에 사용되는 Epic 데이터베이스 스토리지의 권장 사항


이러한 요구사항을 충족하는 고객별 스토리지 시스템 레이아웃 및 구성은 Epic 데이터베이스 스토리지 레이아웃 권장 사항을 참조하여 개발해야 합니다.

다음 예에서는 10TB 데이터베이스를 지원하는 AFF A700 스토리지 시스템의 구축을 설명합니다. 구축 예에서 운영 데이터베이스를 지원하는 데 사용되는 스토리지의 프로비저닝 매개 변수는 아래 표에 나와 있습니다.

|===
| 매개 변수 | 컨트롤러 1 | 컨트롤러 2 


| 컨트롤러 호스트 이름입니다 | prod1-01 | prod1-02 


| 애그리게이트 ONTAP | aggr0_prod1-01(ADP 11 - 파티션) | aggr0_prod1-02(ADP 11 - 파티션) 


| 데이터를 집계합니다 | prod1-01_aggr1(22-파티션) | prod1-02_aggr1(22-파티션) 


| 볼륨(크기) | EPIC_PROD_db1 (2TB) epic_prod_DB2 (2TB) epic_prod_DB3 (2TB) epic_prod_DB5 (2TB) epic_prod_db6 (2TB) epic_prod_DB7 (2TB) epic_prod_DB8 (2TB) epic_prod_inst (1200epic_prod_prod_prod_inst) bd_epic_1200epic_epic_epic_epic_epic_epic_epic_prod_epic | EPIC_REPORT_db1(2TB) epic_report_DB2(2TB) epic_report_db3(2TB) epic_report_db4(2TB) epic_report_db5(2TB) epic_report_db6(2TB) epic_report_db7(2TB) epic_report_db8(2TB) epic_report_inst(1200epic_report_jepic) n2(byte_rereport) 


| LUN 경로(크기) | epic_prod_db1/epic_prod_db1 (1.4TB)/epic_prod_db2/epic_prod_db2/epic_prod_db2 (1.4TB)/epic_prod_db3/epic_db2_prod_db3 (1.4TB) / epic_db4/epic_prod_db5/epic_db5_prod_db5/epic_db5 | epic_prod_db1/epic_report_db1 (1.4TB)/epic_prod_db2/epic_report_db1 (1.4TB)/epic_dbd_db3/epic_report_db3 (1.4TB) / epic_dbst_db4/epic_report_db5/epic_db5/epic_report_db5_db5 (1.4TB_prod_db5) 


| VM | RHEL을 참조하십시오 | RHEL을 참조하십시오 


| LUN 유형입니다 | Linux(FC를 사용하여 RHEL VM에 의해 직접 RDM으로 마운트됨) | Linux(FC를 사용하여 RHEL VM에 의해 직접 RDM으로 마운트됨) 


| FCP 이니시에이터 그룹(igroup) 이름입니다 | IG_epic_prod(Linux) | IG_epic_report(Linux) 


| 호스트 운영 체제입니다 | VMware | VMware 


| EPIC 데이터베이스 서버 호스트 이름입니다 | EPIC_제품 | EPIC_REPORT 


| SVM | SVM_운영 | SVM_PS(운영 서비스) svm_cifs 
|===


=== ONTAP 라이센스

스토리지 컨트롤러를 설정한 후 라이센스를 적용하여 NetApp에서 권장하는 ONTAP 기능을 사용하도록 설정합니다. Epic 워크로드에 필요한 라이센스는 FC, CIFS, Snapshot, SnapRestore, FlexClone, SnapMirror를 사용합니다.

라이센스를 적용하려면 NetApp System Manager를 열고 구성 - 라이센스 로 이동하여 적절한 라이센스를 추가합니다. 또는 다음 명령을 실행하여 CLI를 사용하여 라이센스를 추가합니다.

....
license add -license-code <code>
....


=== AutoSupport 구성

AutoSupport 툴은 HTTPS를 통해 요약 지원 정보를 NetApp에 보냅니다. AutoSupport를 구성하려면 다음 ONTAP 명령을 실행합니다.

....
autosupport modify -node * -state enable
autosupport modify -node * -mail-hosts <mailhost.customer.com>
autosupport modify -node prod1-01 -from prod1-01@customer.com
autosupport modify -node prod1-02 -from prod1-02@customer.com
autosupport modify -node * -to storageadmins@customer.com
autosupport modify -node * -support enable
autosupport modify -node * -transport https
autosupport modify -node * -hostnamesubj true
....


=== 하드웨어 지원 테이크오버 구성

각 노드에서 하드웨어 지원 테이크오버가 발생할 가능성이 낮은 컨트롤러 장애 후 테이크오버 시작에 필요한 시간을 최소화할 수 있도록 합니다. 하드웨어 지원 테이크오버를 구성하려면 다음 단계를 완료합니다.

. 다음 ONTAP 명령을 실행합니다. prod1-01에 대한 관리 포트의 IP 주소로 파트너 주소 옵션을 설정합니다.
+
....
EPIC::> storage failover modify -node prod1-01 -hwassist-partner-ip <prod1-02-mgmt-ip>
....
. 다음 ONTAP 명령을 실행합니다. 파트너 주소 옵션을 cluster1-02에 대한 관리 포트의 IP 주소로 설정합니다.
+
....
EPIC::> storage failover modify -node prod1-02 -hwassist-partner-ip <prod1-01-mgmt-ip>
....
. 다음 ONTAP 명령을 실행하여 prod1-01과 prod1-02 HA 컨트롤러 쌍 모두에서 하드웨어 지원 테이크오버를 설정합니다.
+
....
EPIC::> storage failover modify -node prod1-01 -hwassist true
EPIC::> storage failover modify -node prod1-02 -hwassist true
....




=== ONTAP 스토리지 프로비저닝

스토리지 프로비저닝 워크플로우는 다음과 같습니다.

. 애그리게이트를 생성합니다.
. 스토리지 가상 시스템(SVM)을 생성합니다.
+
Aggregate를 생성한 후 다음 단계는 SVM을 생성하는 것입니다. ONTAP에서는 스토리지가 SVM 형태로 가상화됩니다. 호스트 및 클라이언트는 더 이상 물리적 스토리지 하드웨어에 액세스하지 않습니다. System Manager GUI 또는 CLI를 사용하여 SVM을 생성합니다.

. FC LIF를 생성합니다.
+
포트와 스토리지는 SVM에서 프로비저닝되며 논리 인터페이스(LIF)라는 가상 포트를 통해 호스트 및 클라이언트에 제공됩니다.

+
모든 프로토콜을 사용하여 하나의 SVM에서 모든 워크로드를 실행할 수 있습니다. Epic의 경우 SVM을 사용하여 운영 FC를 수행하고 SVM을 하나씩 사용하여 CIFS를 실행하는 것이 좋습니다.

+
.. System Manager GUI의 SVM 설정에서 FC를 활성화하고 시작합니다.
.. SVM에 FC LIF 추가 LUN별로 아키텍처되는 경로 수에 따라 각 스토리지 노드에서 여러 FC LIF를 구성합니다.


. 이니시에이터 그룹(igroup)을 생성합니다.
+
Igroup은 호스트에 사용할 수 있는 LUN을 정의하는 FC 프로토콜 호스트 WWPN 또는 iSCSI 호스트 노드 이름의 테이블입니다. 예를 들어, 호스트 클러스터가 있는 경우 igroup을 사용하여 특정 LUN이 클러스터의 한 호스트에만 또는 클러스터의 모든 호스트에 표시되는지 확인할 수 있습니다. 여러 igroup을 정의하고 LUN에 매핑하여 LUN에 액세스할 수 있는 이니시에이터를 제어할 수 있습니다.

+
System Manager GUI 또는 CLI를 사용하여 VMware 유형의 FC igroup을 생성합니다.

. FC 스위치에 영역을 생성합니다.
+
FC 또는 FCoE 존은 Fabric에 있는 하나 이상의 포트를 논리적으로 그룹화한 것입니다. 장치가 서로를 보고, 연결하고, 서로 세션을 만들고, 통신하려면 두 포트 모두 공통 영역 구성원 자격을 가져야 합니다. 단일 이니시에이터 조닝을 사용하는 것이 좋습니다.

+
.. 스위치에 영역을 만들고 영역에 NetApp 타겟과 Cisco UCS 블레이드 이니시에이터를 추가합니다.
+
NetApp 모범 사례는 단일 이니시에이터 조닝입니다. 각 존에는 컨트롤러에 하나의 이니시에이터와 타겟 WWPN만 포함되어 있습니다. 존은 노드 이름이 아닌 포트 이름을 사용합니다.



. 볼륨 및 LUN 생성
+
.. System Manager GUI(또는 CLI)를 사용하여 LUN을 호스팅할 볼륨을 생성합니다. 모든 스토리지 효율성 설정 및 데이터 보호는 기본적으로 볼륨에 설정됩니다. 'vol modify' 명령을 사용하여 볼륨에 대한 볼륨 암호화 및 QoS 정책을 선택적으로 설정할 수 있습니다. LUN 및 스냅샷 복사본을 포함할 만큼 볼륨이 커야 합니다. 용량 문제로부터 볼륨을 보호하려면 '자동 크기 조정' 및 '자동 삭제' 옵션을 설정합니다. 볼륨을 생성한 후 Epic 워크로드를 포함할 LUN을 생성합니다.
.. System Manager GUI(또는 CLI)를 사용하여 Epic 워크로드를 호스팅할 유형 VMware의 FC LUN을 생성합니다. NetApp은 System Manager에서 쉽게 따라할 수 있는 마법사를 통해 LUN 생성을 간소화했습니다.
+
VSC를 사용하여 볼륨 및 LUN을 프로비저닝할 수도 있습니다. 를 참조하십시오 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html["ESX Express에 대한 FC 구성 가이드 를 참조하십시오"^].

+
를 참조하십시오 http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-sanag%2Fhome.html["SAN 관리 및 SAN 구성 가이드 를 참조하십시오"^] VSC를 사용하지 않는 경우



. LUN을 igroup에 매핑합니다.
+
LUN 및 igroup을 생성한 후 원하는 호스트가 LUN에 액세스할 수 있도록 해당 igroup에 LUN을 매핑합니다.

+
이제 LUN을 검색할 준비가 되어 ESXi 서버에 매핑할 수 있습니다. ESXi 호스트에서 스토리지를 새로 고치고 새로 검색된 LUN을 추가합니다.



link:ehr-epic-deploy_genio_tool.html["다음: Genio 도구."]
