---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_base_infrastructure_configuration.html 
keywords: base, infrastructure, configuration, network, storage, connections, software, host 
summary: 인프라스트럭처를 구성하려면 다음과 같은 네트워크 접속, 스토리지 접속 및 소프트웨어가 설치되어 있어야 합니다. 
---
= 기본 인프라 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 네트워크 연결

인프라를 구성하기 전에 다음 네트워크 연결이 설정되어야 합니다.

* 포트 채널과 vPC(가상 포트 채널)를 사용하는 링크 집계를 통해 대역폭 및 가용성을 높일 수 있습니다.
+
** VPC는 Cisco FI와 Cisco Nexus 스위치 간에 사용됩니다.
** 각 서버에는 Unified Fabric에 대한 중복 연결 기능을 갖춘 vNIC(Virtual Network Interface Card)가 있습니다. NIC 페일오버는 이중화를 위해 FI 간에 사용됩니다.
** 각 서버에는 Unified Fabric에 대한 이중화 접속 기능을 갖춘 vHBA(Virtual Host Bus Adapter)가 있습니다.


* Cisco UCS FI는 권장 사항에 따라 최종 호스트 모드로 구성되어 업링크 스위치에 vNIC를 동적으로 고정할 수 있습니다.




== 스토리지 연결

인프라스트럭처를 구성하기 전에 다음과 같은 스토리지 접속을 설정해야 합니다.

* 스토리지 포트 인터페이스 그룹(ifgroup, vPC)
* 스위치 N9K-A에 대한 10Gb 링크
* 스위치 N9K-B에 대한 10Gb 링크
* 대역 내 관리(액티브-패시브 결합):
+
** 관리 스위치 N9K-A에 대한 1GB 링크
** 관리 스위치 N9K-B에 대한 1GB 링크


* Cisco MDS 스위치를 통한 32Gb FC 엔드 투 엔드 연결, 단일 이니시에이터 조닝 구성
* 상태 비저장 컴퓨팅을 최대한 실현하기 위한 FC SAN 부팅. 서버는 AFF 스토리지 클러스터에서 호스팅되는 부팅 볼륨의 LUN에서 부팅됩니다
* 모든 MEDITECH 워크로드는 스토리지 컨트롤러 노드에 분산되는 FC LUN에서 호스팅됩니다




== 호스트 소프트웨어

다음 소프트웨어를 설치해야 합니다.

* Cisco UCS 블레이드에 설치된 ESXi
* VMware vCenter 설치 및 구성(vCenter에 등록된 모든 호스트 포함)
* VMware vCenter에 VSC를 설치 및 등록했습니다
* NetApp 클러스터가 구성되었습니다


link:ehr-meditech-deploy_cisco_ucs_blade_server_and_switch_configuration.html["다음: Cisco UCS 블레이드 서버 및 스위치 구성"]
