---
sidebar: sidebar 
permalink: healthcare/ehr-epic-deploy_where_to_find_additional_information_overview.html 
keywords: additional, information, flexpod, deployment, epic, ehr 
summary: 이 문서에 설명된 정보에 대한 자세한 내용은 다음 문서 또는 웹 사이트를 참조하십시오. 
---
= 추가 정보를 찾을 수 있는 위치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


이 문서에 설명된 정보에 대한 자세한 내용은 다음 문서 또는 웹 사이트를 참조하십시오.



== FlexPod 디자인 영역

* FlexPod 디자인 영역
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* NetApp AFF, vSphere 6.5U1 및 Cisco UCS Manager를 사용하는 FC 스토리지(MDS 스위치)가 포함된 FlexPod DC
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html"^]

* Cisco UCS에 대한 Cisco 모범 사례 및 Epic
+
https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf["https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf"^]





== NetApp 기술 보고서

* TR-3929: Reallocate 모범 사례 가이드
+
https://fieldportal.netapp.com/content/192896["https://fieldportal.netapp.com/content/192896"^]

* TR-3987: InterSystems Caché용 Snap Creator Framework 플러그인
+
https://fieldportal.netapp.com/content/248308["https://fieldportal.netapp.com/content/248308"^]

* TR-3928: NetApp Epic 모범 사례
+
https://fieldportal.netapp.com/?oparams=68646["https://fieldportal.netapp.com/?oparams=68646"^]

* TR-4017: FC SAN 모범 사례
+
http://media.netapp.com/documents/tr-4017.pdf["http://media.netapp.com/documents/tr-4017.pdf"^]

* TR-3446: SnapMirror 비동기 개요 및 모범 사례 가이드
+
http://media.netapp.com/documents/tr-3446.pdf["http://media.netapp.com/documents/tr-3446.pdf"^]





== ONTAP 설명서

* NetApp 제품 설명서
+
https://www.netapp.com/us/documentation/index.aspx["https://www.netapp.com/us/documentation/index.aspx"^]

* vSphere용 VSC(Virtual Storage Console) 문서
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048"^]

* ONTAP 9 문서 센터
+
http://docs.netapp.com/ontap-9/index.jsp["http://docs.netapp.com/ontap-9/index.jsp"^]

* ESXi용 FC Express 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html"^]

* 모든 ONTAP 9.3 문서
+
https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579["https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579"^]

+
** 소프트웨어 설치 안내서
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html?lang=dot-cm-ssg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html?lang=dot-cm-ssg"^]

** 디스크 및 애그리게이트 전원 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html?lang=dot-cm-psmg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html?lang=dot-cm-psmg"^]

** SAN 관리 가이드를 참조하십시오
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html?lang=dot-cm-sanag["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html?lang=dot-cm-sanag"^]

** SAN 구성 가이드 를 참조하십시오
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?lang=dot-cm-sanconf["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?lang=dot-cm-sanconf"^]

** Red Hat Enterprise Linux Express용 FC 구성 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html?lang=exp-fc-rhel-cg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html?lang=exp-fc-rhel-cg"^]

** Windows Express용 FC 구성 가이드 를 참조하십시오
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html?lang=exp-fc-cpg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html?lang=exp-fc-cpg"^]

** FC SAN에 최적화된 AFF 설정 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-fcsan-optaff-sg/home.html?lang=cdot-fcsan-optaff-sg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-fcsan-optaff-sg/home.html?lang=cdot-fcsan-optaff-sg"^]

** High-Availability 구성 가이드 를 참조하십시오
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html?lang=dot-cm-hacg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html?lang=dot-cm-hacg"^]

** 논리적 스토리지 관리 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html?lang=dot-cm-vsmg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html?lang=dot-cm-vsmg"^]

** 성능 관리 전원 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html?lang=pow-perf-mon["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html?lang=pow-perf-mon"^]

** SMB/CIFS 구성 전원 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/home.html?lang=pow-cifs-cg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/home.html?lang=pow-cifs-cg"^]

** SMB/CIFS 참조
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html?lang=cdot-famg-cifs["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html?lang=cdot-famg-cifs"^]

** 데이터 보호 전원 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html?lang=pow-dap["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html?lang=pow-dap"^]

** 데이터 보호 테이프 백업 및 복구 가이드
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html?lang=dot-cm-ptbrg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html?lang=dot-cm-ptbrg"^]

** NetApp 암호화 기능 가이드 를 참조하십시오
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html?lang=pow-nve["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html?lang=pow-nve"^]

** 네트워크 관리 가이드 를 참조하십시오
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html?lang=dot-cm-nmg["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html?lang=dot-cm-nmg"^]

** 명령: ONTAP 9.3에 대한 수동 페이지 참조
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/home.html?lang=dot-cm-cmpr-930["http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/home.html?lang=dot-cm-cmpr-930"^]







== Cisco Nexus, MDS, Cisco UCS 및 Cisco UCS Manager 가이드

* Cisco UCS 서버 개요
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html"^]

* Cisco UCS 블레이드 서버 개요
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html"^]

* Cisco UCS B200 M5 데이터시트
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html"^]

* Cisco UCS Manager 개요
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html"^]

* Cisco UCS Manager 3.2(3a) 인프라 번들(Cisco.com 인증 필요)
+
https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529["https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529"^]

* Cisco Nexus 9300 플랫폼 스위치
+
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html"^]

* Cisco MDS 9148S FC 스위치
+
https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html["https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html"^]


