---
sidebar: sidebar 
permalink: healthcare/ehr-epic-performance_executive_summary.html 
keywords: epic, performance, storage, efficiency, all, flash, fas, platform, ehr 
summary: NetApp은 NetApp All Flash FAS 플랫폼의 스토리지 효율성과 성능을 보여주기 위해 AFF A300 및 AFF A700 시스템에서 Epic EHR 성능을 측정하기 위한 연구를 수행했습니다. 
---
= 핵심 요약
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp은 NetApp All Flash FAS 플랫폼의 스토리지 효율성과 성능을 보여주기 위해 AFF A300 및 AFF A700 시스템에서 Epic EHR 성능을 측정하기 위한 연구를 수행했습니다. NetApp은 ONTAP 9.4를 실행하는 AFF A300 및 AFF A700 스토리지 컨트롤러, 각각 Epic EHR 워크로드를 실행하는 ONTAP A300의 데이터 처리량, 최대 IOPS, 평균 지연 시간을 측정했습니다. SPC-3 테스트와 비슷한 방식으로 모든 인라인 스토리지 효율성 기능을 사용할 수 있었습니다.

총 3.8TB SSD가 포함된 AFF A300 클러스터와 총 48개 3.8TB SSD가 포함된 AFF A700 클러스터에서 Epic Genio 워크로드 생성기를 실행했습니다. 우리는 스토리지를 최고 CPU 활용률로 몰아넣은 다양한 로드 지점에서 클러스터를 테스트했습니다. 각 로드 지점에서 스토리지 IOPS 및 지연 시간에 대한 정보를 수집했습니다.

NetApp은 소프트웨어 업그레이드 때마다 성능이 40~50% 범위에서 일관되게 좋아졌습니다. 성능 향상을 통한 혁신은 워크로드와 프로토콜에 따라 다릅니다.

Epic 성능 테스트를 통해 AFF A300 클러스터 IOPS가 1ms 미만에서 75,000 IOPS에서 1ms 미만의 최대 성능으로 188,929 IOPS의 성능을 보였다는 사실을 확인할 수 있었습니다. 200,000 IOPS 이하의 모든 로드 지점에서 1ms 미만의 일관된 스토리지 지연 시간을 유지할 수 있었습니다. 또한 Epic 성능 테스트를 통해 AFF A700 클러스터 IOPS가 1ms 미만에서 75,000 IOPS에서 1ms 미만의 최대 성능으로 319,000 IOPS의 성능을 보였다는 사실을 입증했습니다. 320,000 IOPS 이하의 모든 로드 지점에서 1ms의 스토리지 지연 시간을 일관되게 유지할 수 있었습니다.
