---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-sizing_meditech_workload_overview.html 
keywords: meditech, workload, backup, cisco, ucs, reference, architecture, platforms 
summary: 이 섹션에서는 MEDITECH 환경에서 얻을 수 있는 컴퓨팅 및 스토리지 워크로드의 유형에 대해 설명합니다. 
---
= MEDITECH 워크로드 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


이 섹션에서는 MEDITECH 환경에서 얻을 수 있는 컴퓨팅 및 스토리지 워크로드의 유형에 대해 설명합니다.



== MEDITECH 및 백업 워크로드

MEDITECH 환경에 맞게 NetApp 스토리지 시스템을 사이징할 때는 MEDITECH 운영 워크로드와 백업 워크로드를 모두 고려해야 합니다.

|===
| MEDITECH 호스트 


| MEDITECH 호스트는 데이터베이스 서버입니다. 이 호스트는 MEDITECH 파일 서버(광활함, 6.x 또는 C/S 5.x 플랫폼) 또는 Magic 시스템(매직 플랫폼)이라고도 합니다. 이 문서에서는 MEDITECH 호스트라는 용어를 사용하여 MEDITECH 파일 서버 및 Magic 시스템을 참조합니다. 
|===
다음 섹션에서는 이러한 두 워크로드의 I/O 특성 및 성능 요구사항에 대해 설명합니다.



== MEDITECH 워크로드

MEDITECH 환경에서 MEDITECH 소프트웨어를 실행하는 여러 서버는 MEDITECH 시스템이라는 통합 시스템으로 다양한 작업을 수행합니다. MEDITECH 시스템에 대한 자세한 내용은 MEDITECH 설명서를 참조하십시오.

* 프로덕션 MEDITECH 환경의 경우 해당 MEDITECH 설명서를 참조하여 NetApp 스토리지 시스템 사이징에 포함되어야 하는 MEDITECH 호스트 수와 스토리지 용량을 확인하십시오.
* 새 MEDITECH 환경의 경우 하드웨어 구성 제안 문서를 참조하십시오. 기존 MEDITECH 환경의 경우 하드웨어 평가 작업 문서를 참조하십시오. 하드웨어 평가 작업은 MEDITECH 티켓과 연결됩니다. 고객은 MEDITECH에서 이러한 문서 중 하나를 요청할 수 있습니다.


호스트를 추가하여 용량과 성능을 향상시키도록 MEDITECH 시스템을 확장할 수 있습니다. 각 호스트에는 데이터베이스 및 애플리케이션 파일을 위한 스토리지 용량이 필요합니다. 각 MEDITECH 호스트에서 사용할 수 있는 스토리지는 호스트에서 생성된 입출력도 지원해야 합니다. MEDITECH 환경에서는 각 호스트에 대해 LUN을 사용하여 해당 호스트의 데이터베이스 및 애플리케이션 스토리지 요구 사항을 지원할 수 있습니다. MEDITECH 범주의 유형과 배포하는 플랫폼 유형에 따라 각 MEDITECH 호스트와 시스템 전체의 워크로드 특성이 결정됩니다.



=== MEDITECH 범주

MEDITECH는 배포 크기를 1에서 6 사이의 범주 번호와 연결합니다. 범주 1은 가장 작은 MEDITECH 배포이며 범주 6은 가장 큰 배포입니다. 각 범주와 관련된 MEDITECH 애플리케이션 사양의 예로는 다음과 같은 메트릭이 있습니다.

* 병원 침대 수
* 연간 입원 환자 수
* 연간 외래 환자 수
* 매년 응급실 방문
* 연간 검사 횟수
* 1일 입원 환자 처방
* 외래 환자 처방전/일일


MEDITECH 범주에 대한 자세한 내용은 MEDITECH 범주 참조 시트를 참조하십시오. MEDITECH에서 고객 또는 MEDITECH 시스템 설치 프로그램을 통해 이 시트를 얻을 수 있습니다.



=== MEDITECH 플랫폼

MEDITECH의 4가지 플랫폼:

* 드넓은 공간을 제공합니다
* MEDITECH 6.x
* 클라이언트/서버 5.x(C/S 5.x)
* 마법


MEDITECH의 경우, 6.x 및 C/S 5.x 플랫폼의 경우 각 호스트의 입출력 특성이 요청 크기가 4,000인 100% 랜덤으로 정의됩니다. MEDITECH Magic 플랫폼의 경우 각 호스트의 입출력 특성은 요청 크기가 8,000 또는 16,000인 100% 랜덤으로 정의됩니다. MEDITECH에 따르면 일반적인 매직 프로덕션 배포의 요청 크기는 8,000 또는 16,000입니다.

읽기 및 쓰기 비율은 구축하는 플랫폼에 따라 다릅니다. MEDITECH는 읽기 및 쓰기의 평균 조합을 추정하고 백분율로 표시합니다. 또한 MEDITECH는 특정 MEDITECH 플랫폼의 각 MEDITECH 호스트에 필요한 평균 지속 IOPS 값을 예측합니다. 아래 표에는 MEDITECH에서 제공하는 플랫폼별 I/O 특성이 요약되어 있습니다.

|===
| MEDITECH 범주 | MEDITECH 플랫폼 | 평균 랜덤 읽기 % | 평균 랜덤 쓰기 % | MEDITECH 호스트당 평균 지속 IOPS 


| 1 | 드넓은 6.x | 20 | 80 | 750입니다 


.4+| 2-6 | 드넓은 공간을 제공합니다 | 20 | 80 | 750입니다 


| 6.x | 20 | 80 | 750입니다 


| C/S 5.x | 40 | 60 | 600 


| 마법 | 90 | 10 | 400 
|===
MEDITECH 시스템에서 각 호스트의 평균 IOPS 레벨은 위 표에 정의된 IOPS 값과 같아야 합니다. 각 플랫폼을 기반으로 올바른 스토리지 사이징을 결정하려면 위의 표에 지정된 IOPS 값이 에 설명된 사이징 방법론의 일부로 사용됩니다 link:ehr-meditech-sizing_technical_specifications_for_small,_medium_and_large_architectures.html["소규모, 중간 규모 및 대규모 아키텍처에 대한 기술 사양"] 섹션을 참조하십시오.

MEDITECH는 각 호스트에 대해 평균 랜덤 쓰기 지연 시간을 1ms 미만으로 유지해야 합니다. 그러나 백업 및 재할당 작업 중에 쓰기 지연 시간을 최대 2ms까지 일시적으로 늘릴 수 있는 것으로 간주됩니다. 또한 MEDITECH는 범주 1 호스트의 경우 평균 랜덤 읽기 지연 시간이 7ms 미만이고 범주 2 호스트의 경우 5ms 미만이어야 합니다. 이러한 지연 시간 요구 사항은 어떤 MEDITECH 플랫폼을 사용하는지에 관계없이 모든 호스트에 적용됩니다.

아래 표에는 MEDITECH 워크로드에 대한 NetApp 스토리지의 크기를 조정할 때 고려해야 하는 I/O 특성이 요약되어 있습니다.

|===
| 매개 변수 | MEDITECH 범주 | 드넓은 공간을 제공합니다 | MEDITECH 6.x | C/S 5.x | 마법 


| 요청 크기입니다 .2+| 1-6 | 4K | 4K | 4K | 8K 또는 16K 


| 랜덤/순차 | 100% 랜덤 | 100% 랜덤 | 100% 랜덤 | 100% 랜덤 


.2+| 평균 지속 IOPS | 1 | 750입니다 | 750입니다 | 해당 없음 | 해당 없음 


| 2-6 | 750입니다 | 750입니다 | 600 | 400 


| 읽기/쓰기 속도 .2+| 1-6 | 20% 읽기, 80% 쓰기 | 20% 읽기, 80% 쓰기 | 40% 읽기, 60% 쓰기 | 90% 읽기, 10% 쓰기 


| 쓰기 지연 시간 | 1ms 미만 | 1ms 미만 | 1ms 미만 | 1ms 미만 


| 일시적인 최대 쓰기 지연 시간입니다 | 1-6 | 2ms 미만 | 2ms 미만 | 2ms 미만 | 2ms 미만 


.2+| 읽기 지연 시간 | 1 | 7ms 미만 | 7ms 미만 | 해당 없음 | 해당 없음 


| 2-6 | 5ms 미만 | 5ms 미만 | 5ms 미만 | 5ms 미만 
|===

NOTE: 범주 3에서 6까지의 MEDITECH 호스트는 범주 2와 동일한 I/O 특성을 갖습니다. MEDITECH 범주 2 - 6의 경우 각 범주에 구축된 호스트 수가 다릅니다.

NetApp 스토리지 시스템은 이전 섹션에서 설명한 성능 요구사항을 충족할 수 있도록 사이징해야 합니다. NetApp 스토리지 시스템은 MEDITECH 운영 워크로드 외에도 다음 섹션에 설명된 대로 백업 작업 중에 이러한 MEDITECH 성능 목표를 유지할 수 있어야 합니다.



== 백업 워크로드 설명

MEDITECH 인증 백업 소프트웨어는 MEDITECH 시스템의 각 MEDITECH 호스트에서 사용하는 LUN을 백업합니다. 백업이 애플리케이션 정합성 보장 상태에 있도록 백업 소프트웨어는 MEDITECH 시스템을 중지시키고 디스크에 대한 입출력 요청을 일시 중단합니다. 시스템이 중지 상태에 있는 동안 백업 소프트웨어는 NetApp 스토리지 시스템에 명령을 발행하여 LUN이 포함된 볼륨의 NetApp 스냅샷 복사본을 생성합니다. 나중에 백업 소프트웨어가 MEDITECH 시스템을 중지하여 운영 I/O 요청을 데이터베이스로 계속 진행할 수 있도록 합니다. 스냅샷 복사본을 기반으로 NetApp FlexClone 볼륨이 생성됩니다. 이 볼륨은 LUN을 호스팅하는 상위 볼륨에서 운영 입출력 요청이 계속 진행되는 동안 백업 소스에서 사용됩니다.

백업 소프트웨어에서 생성되는 워크로드는 FlexClone 볼륨에 상주하는 LUN을 순차적으로 읽음으로써 발생합니다. 워크로드는 요청 크기가 64,000인 100% 순차적 읽기 워크로드로 정의됩니다. MEDITECH 운영 워크로드의 성능 기준은 필요한 IOPS 및 관련 읽기/쓰기 지연 시간 수준을 유지하는 것입니다. 그러나 백업 워크로드의 경우 백업 작업 중에 생성되는 전체 데이터 처리량(MBps)으로 주의를 이동합니다. MEDITECH LUN 백업은 8시간 백업 기간에 완료되어야 하지만, NetApp은 모든 MEDITECH LUN 백업을 6시간 이내에 완료할 것을 권장합니다. 백업을 6시간 이내에 완료하는 것을 목표로 MEDITECH 워크로드의 계획되지 않은 증가, NetApp ONTAP 백그라운드 작업 또는 시간의 경과에 따른 데이터 증가와 같은 이벤트를 완화합니다. 이러한 이벤트 중 하나라도 발생하면 추가 백업 시간이 발생할 수 있습니다. 백업 소프트웨어는 저장된 애플리케이션 데이터의 양에 관계없이 각 MEDITECH 호스트에 대해 전체 LUN의 블록 레벨 백업을 수행합니다.

이 창 내에서 백업을 완료하는 데 필요한 순차적 읽기 처리량을 계산하는 방법은 다음과 같은 다른 요인의 기능입니다.

* 원하는 백업 기간
* LUN의 수입니다
* 백업할 각 LUN의 크기입니다


예를 들어 각 호스트의 LUN 크기가 200GB인 50개 호스트 MEDITECH 환경에서는 백업할 총 LUN 용량이 10TB입니다.

10TB의 데이터를 8시간 내에 백업하려면 다음과 같은 처리량이 필요합니다.

* = (10 x 10^6)MB(8 x 3,600)s
* = 347.2MBps


그러나 예상치 못한 이벤트를 고려하여 6시간 이상의 여유 공간을 제공하기 위해 5.5시간의 보수적인 백업 윈도우가 선택됩니다.

10TB의 데이터를 8시간 내에 백업하려면 다음과 같은 처리량이 필요합니다.

* = (10 x 10^6) MB(5.5 x 3,600)s
* = 500Mbps


500Mbps의 처리량에서 5.5시간 이내에 백업을 완료할 수 있으며, 8시간의 백업 요구 사항에서도 편안하게 백업이 가능합니다.

아래 표에는 스토리지 시스템의 크기를 조정할 때 사용할 백업 워크로드의 I/O 특성이 요약되어 있습니다.

|===
| 매개 변수 | 모든 플랫폼 


| 요청 크기입니다 | 64K 


| 랜덤/순차 | 100% 순차적 


| 읽기/쓰기 속도 | 100% 읽기 


| 평균 처리량 | MEDITECH 호스트의 수와 각 LUN의 크기에 따라 백업이 8시간 이내에 완료되어야 합니다. 


| 백업 기간이 필요합니다 | 8시간 
|===


== MEDITECH용 Cisco UCS 참조 아키텍처

MEDITECH on FlexPod의 아키텍처는 MEDITECH, Cisco 및 NetApp의 지침과 모든 규모의 MEDITECH 고객과 협력하는 파트너 경험을 바탕으로 합니다. 이 아키텍처는 고객의 데이터 센터 전략(소규모 또는 대규모, 중앙 집중식, 분산 또는 멀티 테넌트)에 따라 적응 가능하며 MEDITECH의 모범 사례를 적용합니다.

MEDITECH를 배포할 때 Cisco는 MEDITECH의 모범 사례와 직접 일치하는 Cisco UCS 참조 아키텍처를 설계했습니다. Cisco UCS는 고성능, 고가용성, 안정성, 확장성을 위해 긴밀하게 통합된 솔루션을 제공하여 수천 개의 병상을 보유한 의사 및 병원 시스템을 지원합니다.
