---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_aggregate_configuration.html 
keywords: aggregate, configuration, raid, groups, dp, storage, expansion, snapshot, copy, 
summary: NetApp RAID DP 기술은 일반 NetApp Flash Pool 애그리게이트를 포함하여 NetApp FAS 또는 AFF 시스템의 모든 애그리게이트를 위한 RAID 유형으로 권장됩니다. MEDITECH 설명서에 RAID 10의 사용이 지정되어 있을 수 있지만 MEDITECH는 RAID DP 사용을 승인했습니다. 
---
= 애그리게이트 구성
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== NetApp RAID DP를 참조하십시오

NetApp RAID DP 기술은 일반 NetApp Flash Pool 애그리게이트를 포함하여 NetApp FAS 또는 AFF 시스템의 모든 애그리게이트를 위한 RAID 유형으로 권장됩니다. MEDITECH 설명서에 RAID 10의 사용이 지정되어 있을 수 있지만 MEDITECH는 RAID DP 사용을 승인했습니다.



== RAID 그룹 크기 및 RAID 그룹 수

기본 RAID 그룹 크기는 16입니다. 이 크기는 특정 사이트의 MEDITECH 호스트에 대한 집계를 위한 최적의 크기일 수도 있고 그렇지 않을 수도 있습니다. RAID 그룹에 사용할 것을 권장한 디스크 수에 대해서는 를 참조하십시오 https://fieldportal.netapp.com/content/190829["NetApp TR-3838: 스토리지 서브시스템 구성 가이드"^].

RAID 그룹 크기와 RAID 그룹 크기가 같은 하나 이상의 디스크 그룹이 있는 애그리게이트에 디스크를 추가하는 것이 권장되므로 스토리지 확장에는 RAID 그룹 크기가 중요합니다. RAID 그룹 수는 데이터 디스크 수와 RAID 그룹 크기에 따라 달라집니다. 필요한 데이터 디스크의 수를 확인하려면 SPM(NetApp System Performance Modeler) 사이징 툴을 사용하십시오. 데이터 디스크 수를 결정한 후 RAID 그룹 크기를 조정하여 디스크 유형당 RAID 그룹 크기에 대해 권장되는 범위 내에서 패리티 디스크 수를 최소화합니다.

MEDITECH 환경에 SPM 사이징 툴을 사용하는 방법에 대한 자세한 내용은 을 참조하십시오 https://fieldportal.netapp.com/content/198446["NetApp TR-4190: MEDITECH 환경을 위한 NetApp 사이징 지침"^].



== 스토리지 확장 고려 사항

더 많은 디스크로 애그리게이트를 확장할 경우, 애그리게이트 RAID 그룹 크기와 같은 그룹으로 디스크를 추가하십시오. 이 방법을 따라하면 애그리게이트 전체에서 성능 일관성을 제공할 수 있습니다.

예를 들어, RAID 그룹 크기가 20인 Aggregate에 스토리지를 추가하려면 NetApp에서 권장하는 디스크 수는 하나 이상의 20-디스크 그룹입니다. 디스크를 20, 40, 60 등으로 추가해야 합니다.

애그리게이트를 확장한 후에는 영향을 받는 볼륨에서 재할당 작업을 실행하거나, 애그리게이트를 실행하여 기존 데이터 스트라이프를 새 디스크에 분산하여 성능을 향상할 수 있습니다. 이 작업은 특히 기존 집계가 거의 가득 찬 경우 유용합니다.


NOTE: 비운영 시간 동안에는 CPU 및 디스크 사용량이 많은 작업이므로 일정 재할당을 계획해야 합니다.

애그리게이트 확장 후 재할당을 사용하는 방법에 대한 자세한 내용은 를 참조하십시오 https://fieldportal.netapp.com/content/192896["NetApp TR-3929: 재할당 모범 사례 가이드"^].



== Aggregate 레벨의 Snapshot 복사본

Aggregate 레벨의 NetApp 스냅샷 복사본 예약 공간을 0으로 설정하고 기본 애그리게이트 스냅샷 스케줄을 비활성화합니다. 가능하면 기존의 모든 애그리게이트 레벨 스냅샷 복사본을 삭제합니다.

link:ehr-meditech-deploy_storage_virtual_machine_configuration.html["다음: 스토리지 가상 머신 구성"]
