---
sidebar: sidebar 
permalink: ent-db/fpd-sap-ucs-aff.html 
keywords: flexpod, cisco, data, center, sap, ucs, aff, a-series, tdi, tailored, design 
summary: '이 문서에서는 SAP HANA TDI(Tailored Data Center Integration) 환경을 구축하기 위해 검증된 접근 방식인 Cisco 및 NetApp FlexPod 솔루션에 대해 설명합니다.' 
---
= Cisco UCS Manager 4.0 및 NetApp AFF A-Series-Design을 사용하는 SAP용 FlexPod 데이터 센터 솔루션
:allow-uri-read: 


Pramod Ramamurhy, Cisco Marco Schoen, NetApp

이 문서에서는 SAP HANA TDI(Tailored Data Center Integration) 환경을 구축하기 위해 검증된 접근 방식인 Cisco 및 NetApp FlexPod 솔루션에 대해 설명합니다. 검증된 이 설계는 Cisco 및 NetApp의 모범 사례를 바탕으로 SAP HANA를 구축하기 위한 지침과 프레임워크를 제공합니다.

FlexPod은 광범위한 엔터프라이즈 워크로드 및 사용 사례를 지원하는 업계 최고의 통합 인프라입니다. 이 솔루션을 사용하면 맞춤형 데이터 센터 통합 모드 모델을 통해 SAP HANA를 빠르고 안정적으로 구축할 수 있습니다.

권장되는 솔루션 아키텍처는 Cisco UCS(Unified Computing System)에서 다음 구성 요소가 포함된 Cisco UCS 하드웨어 플랫폼을 지원하는 통합 소프트웨어 릴리즈를 사용합니다.

* Cisco UCS B-Series 블레이드 서버 및 Cisco UCS C-Series 랙 서버는 Intel Optane Data Center DCPMM(Persistent Memory Module) 옵션으로 구성할 수 있습니다
* Cisco UCS 6300 시리즈 Fabric Interconnect
* Cisco Nexus 9000 시리즈 스위치
* NetApp All Flash 시리즈 스토리지 어레이를 제공할 좋은 기회입니다


또한 이 문서에서는 Red Hat Enterprise Linux 및 SAP HANA용 SUSE Linux Enterprise Server 모두에 대한 유효성 검사를 제공합니다.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_sap_netappaffa_design.html["Cisco UCS Manager 4.0 및 NetApp AFF A-Series-Design을 사용하는 SAP용 FlexPod 데이터 센터 솔루션"^]
