---
sidebar: sidebar 
permalink: ent-db/fpd-sap-sql.html 
keywords: flexpod, cisco, white, paper,sap, non-hana, sql 
summary: 현재 IT 업계에서 데이터 센터 솔루션의 획기적인 변화가 목격되고 있습니다. 
---
= SAP 비 HANA with SQL 백서 - 설계
:allow-uri-read: 


[role="lead"]
현재 IT 업계에서 데이터 센터 솔루션의 획기적인 변화가 목격되고 있습니다. 최근 몇 년간 사전 검증되고 엔지니어링된 데이터 센터 솔루션에 상당한 관심이 있었습니다. 중요 영역에 가상화 기술을 도입함으로써 이러한 솔루션의 설계 원칙과 아키텍처에 상당한 영향을 미쳤습니다. 따라서 베어 메탈 시스템에서 실행 중인 많은 애플리케이션을 새로운 가상화 통합 솔루션으로 마이그레이션할 수 있었습니다. FlexPod는 IT 부서의 빠르게 변화하는 요구사항을 해결하기 위해 사전 검증되고 엔지니어링된 데이터 센터 솔루션 중 하나입니다. Cisco와 NetApp은 파트너십을 통해 데이터베이스, ERP(전사적 자원 관리), CRM(고객 관계 관리) 및 웹 애플리케이션을 포함한 다양한 엔터프라이즈 워크로드를 위한 기반으로 동급 최고의 컴퓨팅, 네트워킹 및 스토리지 구성요소를 사용하는 FlexPod를 제공하고 있습니다.

IT 애플리케이션, 특히 데이터베이스의 통합은 최근 몇 년 동안 상당한 관심을 불러왔습니다. 지난 몇 년 동안 가장 널리 채택되고 배포된 데이터베이스 플랫폼은 Microsoft SQL Server입니다. SQL Server 데이터베이스는 종종 데이터베이스의 무분별한 확장을 수반하며, 이에 따라 서버 활용도가 낮은 문제, 잘못된 라이센싱, 보안 문제, 관리 문제, 막대한 운영 비용 등과 같은 IT 과제도 발생합니다. 따라서 SQL Server 데이터베이스는 보다 강력하고 유연하며 복원력이 뛰어난 플랫폼에 통합할 수 있는 적합합니다. 이 문서에서는 SQL Server 데이터베이스의 배포 및 통합을 위한 FlexPod 참조 아키텍처에 대해 설명합니다.

link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf["SAP 비 HANA with SQL 백서 - 설계"^]
