---
sidebar: sidebar 
permalink: ent-db/fpd-sap-aci-aseries-design.html 
keywords: flexpod, cisco, sap, aci, UCS manager, aff, a-series, tdi, sap, hana 
summary: '이 문서에서는 SAP HANA TDI(Tailored Data Center Integration) 환경을 구축하기 위한 검증된 접근 방법으로 Cisco ACI 통합 FlexPod 솔루션에 대해 설명합니다.' 
---
= Cisco ACI, Cisco UCS Manager 4.0 및 NetApp AFF A-Series-Design이 포함된 SAP용 FlexPod 데이터 센터 솔루션
:allow-uri-read: 


Pramod Ramamurhy, Cisco Marco Schoen, NetApp

이 문서에서는 SAP HANA TDI(Tailored Data Center Integration) 환경을 구축하기 위한 검증된 접근 방법으로 Cisco ACI 통합 FlexPod 솔루션에 대해 설명합니다. 검증된 이 설계는 Cisco 및 NetApp의 모범 사례를 바탕으로 SAP HANA를 구축하기 위한 지침과 프레임워크를 제공합니다.

권장되는 솔루션 아키텍처는 Cisco UCS(Unified Computing System)에서 다음 구성 요소가 포함된 Cisco UCS 하드웨어 플랫폼을 지원하는 통합 소프트웨어 릴리즈를 사용합니다.

* Intel Optane Data Center DCPMM(Persistent Memory Module) 옵션으로 구성할 수 있는 Cisco UCS B-Series 블레이드 서버 및 Cisco UCS C-Series 랙 서버
* Cisco UCS 6400 시리즈 패브릭 인터커넥트
* Cisco Nexus 9000 Series Leaf 및 Spine 스위치
* NetApp All Flash 시리즈 스토리지 어레이를 제공할 좋은 기회입니다


또한 이 문서에서는 Red Hat Enterprise Linux 및 SAP HANA용 SUSE Linux Enterprise Server 모두에 대한 검증을 제공합니다.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_ACI_sap_netappaffa_design.html["Cisco ACI, Cisco UCS Manager 4.0 및 NetApp AFF A-Series-Design이 포함된 SAP용 FlexPod 데이터 센터 솔루션"^]
