---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: Cisco의 검증된 설계에는 고객 배포를 촉진하고 개선하기 위해 설계, 테스트 및 문서화된 시스템 및 솔루션이 포함됩니다. 
---
= Cisco UCS 및 NetApp AFF A-Series에서 Oracle RAC 데이터베이스가 지원되는 FlexPod 데이터 센터
:allow-uri-read: 


Tushar Patel, Cisco Hardikkumar Vyas

Cisco의 검증된 설계에는 고객 배포를 촉진하고 개선하기 위해 설계, 테스트 및 문서화된 시스템 및 솔루션이 포함됩니다. 이러한 설계는 고객의 비즈니스 요구를 해결하기 위해 개발된 솔루션 포트폴리오에 광범위한 기술과 제품을 통합합니다. Cisco와 NetApp은 파트너십을 통해 FlexPod 다양한 워크로드의 기반 역할을 하며 고객 요구사항을 기반으로 효율적인 아키텍처 설계를 지원합니다. FlexPod 솔루션은 Cisco 및 NetApp 기술을 공유 클라우드 인프라로 구축하기 위한 검증된 접근 방식입니다.

NetApp All Flash AFF 시스템을 지원하는 FlexPod 데이터 센터는 Cisco와 NetApp의 동급 최고 기술을 엔터프라이즈 애플리케이션을 위한 강력한 통합 플랫폼으로 결합하는 통합 인프라 플랫폼입니다. Cisco와 NetApp은 Oracle과 긴밀하게 협력하여 오늘날의 비즈니스에 필요한 가장 까다로운 트랜잭션 및 응답 시간에 민감한 데이터베이스를 지원합니다.

CVD(Cisco Validated Design)에서는 고가용성 Oracle RAC 데이터베이스 환경을 구축하기 위해 Cisco UCS 및 NetApp All Flash AFF 스토리지를 사용하는 참조 FlexPod 데이터 센터 아키텍처에 대해 설명합니다. 이 문서에서는 관련된 구성 요소의 하드웨어 및 소프트웨어 구성과 다양한 테스트 결과를 보여 줍니다. 또한 Cisco UCS 컴퓨팅 서버, Cisco Fabric Interconnect 스위치, Cisco MDS 스위치, Cisco Nexus 스위치, NetApp AFF 스토리지 및 Oracle RAC 데이터베이스를 사용하는 구현 및 모범 사례 지침을 제공합니다.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["Cisco UCS 및 NetApp AFF A-Series에서 Oracle RAC 데이터베이스가 지원되는 FlexPod 데이터 센터"^]
