---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: Cisco Intersight와 NetApp ONTAP 스토리지 통합을 위한 하드웨어, 소프트웨어 및 라이센스 요구사항이 충족되는지 확인합니다. 
---
= 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp ONTAP 스토리지를 Cisco Intersight와 통합하기 위한 하드웨어, 소프트웨어 및 라이센스 요구사항을 충족하는지 확인합니다.



== 하드웨어 및 소프트웨어 요구 사항

이러한 구성 요소는 솔루션을 구축하는 데 필요한 최소 하드웨어 및 소프트웨어 구성 요소입니다. 솔루션의 특정 구현에 사용되는 구성 요소는 고객의 요구 사항에 따라 다를 수 있습니다.

|===
| 구성 요소 | 요구사항 세부 정보 


| NetApp ONTAP를 참조하십시오 | ONTAP 9.7P1 이상 


| NetApp Active IQ Unified Manager를 참조하십시오 | 최신 버전의 NetApp Active IQ Unified Manager가 필요합니다(현재 9.14RC1). 


| NetApp 스토리지 어레이 | ONTAP 9.7P1 이상에서 모든 ONTAP ASA, AFF 및 FAS 스토리지 어레이를 지원합니다 


| 가상화 하이퍼바이저 | vSphere 7.0 이상 
|===

NOTE: 을 참조하십시오 https://intersight.com/help/saas/supported_systems["Cisco Intersight 지원 시스템"^] Cisco UCS Compute Components 및 UCSM 버전의 최소 요구 사항



== Cisco Intersight 라이센스 요구 사항

Cisco Intersight는 물리적 스토리지(NetApp 스토리지)를 관리, 자동화, 최적화하는 인프라 서비스 및 Cloud Orchestrator 서비스와 같은 서비스를 제공합니다. 이 서비스를 사용하여 Cisco UCS 서버 및 Cisco HyperFlex 시스템을 관리할 수 있습니다. Infrastructure Service 및 Cloud Orchestrator 서비스는 여러 계층의 구독 기반 라이센스 모델을 사용합니다. 선택한 구독 기간에 필요한 Cisco UCS Server 볼륨 계층을 선택할 수 있습니다.

.라이센스 모델
Cisco Intersight Infrastructure Services 라이센스 모델이 간소화되었으며, 이제 다음 두 개의 계층을 제공합니다.

* * Cisco Intersight Infrastructure Services Essentials * - Essentials 라이센스 계층은 글로벌 상태 모니터링 기능, 인벤토리, Cisco TAC 통합을 통한 사전 지원, 다중 요소 인증, SDK 및 API 액세스를 제공하는 등의 서버 관리를 제공합니다.
* * Cisco Intersight Infrastructure Services Advantage * - Advantage 라이센스 계층은 확장된 가시성, 에코시스템 통합, Cisco 및 타사 하드웨어 및 소프트웨어 자동화와 다중 도메인 솔루션을 제공하는 고급 서버 관리를 제공합니다.


다양한 라이센스 계층에서 지원하는 기능에 대한 자세한 내용은 를 참조하십시오 https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["인프라 서비스 라이센스"^].
