---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: Cisco Intersight와 NetApp ONTAP 스토리지 통합을 위한 하드웨어, 소프트웨어 및 라이센스 요구사항이 충족되는지 확인합니다. 
---
= 요구 사항
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cisco Intersight와 NetApp ONTAP 스토리지 통합을 위한 하드웨어, 소프트웨어 및 라이센스 요구사항이 충족되는지 확인합니다.



== 하드웨어 및 소프트웨어 요구 사항

이러한 구성 요소는 솔루션을 구축하는 데 필요한 최소 하드웨어 및 소프트웨어 구성 요소입니다. 솔루션의 특정 구현에 사용되는 구성 요소는 고객의 요구 사항에 따라 다를 수 있습니다.

|===
| 구성 요소 | 요구사항 세부 정보 


| NetApp ONTAP를 참조하십시오 | ONTAP 9.7P1 이상 


| NetApp Active IQ Unified Manager를 참조하십시오 | NetApp Active IQ Unified Manager의 최신 버전 권장(현재 9.10P1) 


| NetApp 스토리지 어레이 | ONTAP 9.7P1 이상에서 모든 ONTAP ASA, AFF 및 FAS 스토리지 어레이가 지원됩니다 


| 가상화 하이퍼바이저 | vSphere 6.7 이상 
|===

NOTE: 을 참조하십시오 https://www.cisco.com/c/en/us/solutions/collateral/data-center-virtualization/flexpod/cisco-imm-for-flexpod.html["FlexPod용 Cisco Intersight 관리 모드"^] Cisco UCS Compute Components 및 UCSM 버전의 최소 요구 사항



== Cisco Intersight 라이센스 요구 사항

Cisco Intersight는 선택할 수 있는 여러 라이센스 에디션과 함께 구독 기반으로 라이센스가 부여됩니다. 다양한 라이센스 유형에 따라 기능이 향상됩니다. 1년, 3년 또는 5년의 구독 기간을 구입하고 선택한 구독 기간에 필요한 Cisco UCS Server 볼륨 계층을 선택할 수 있습니다. Cisco Intersight 포털에 액세스하여 장치를 요청할 때 각 Cisco 끝점에 추가 비용 없이 Cisco Intersight Base가 자동으로 포함됩니다.

Cisco 주문 툴을 사용하여 다음과 같은 상위 계층 Intersight 라이센스를 구입할 수 있습니다.

* * Cisco Intersight Essentials. * Essentials는 Cisco UCS Central 및 Cisco IMC Supervisor 자격, 서비스 프로필을 사용한 정책 기반 구성, 펌웨어 관리, HCL(하드웨어 호환성 목록)과의 호환성 평가 등 추가 기능과 함께 기본 계층의 모든 기능을 포함합니다.
* * Cisco Intersight Advantage. * Advantage는 Base 및 Essentials 계층의 모든 기능과 특징을 제공합니다. 여기에는 스토리지 위젯, 스토리지 인벤토리, 스토리지 용량 및 스토리지 사용률, 물리적 컴퓨팅, 물리적 스토리지 및 가상 환경(VMware ESXi)에 걸친 도메인 간 인벤토리 상관 관계가 포함됩니다.
* * Cisco Intersight Premier. * Cisco Intersight Premier는 Advantage 계층에서 제공되는 기능 외에도 Cisco UCS 및 VM(가상 머신)(VMware vCenter) 및 물리적 스토리지(NetApp 스토리지)를 포함한 타사 시스템에서 프라이빗 클라우드 IaaS(서비스로서의 인프라) 오케스트레이션을 제공합니다.


다양한 라이센스 계층에서 지원하는 기능에 대한 자세한 내용은 를 참조하십시오 https://intersight.com/help/getting_started#intersight_licensing["Cisco 라이센스"].
